//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01", IsNullable=false)]
public partial class Document {
    
    private SettlementFailsMonthlyReportV01 sttlmFlsMnthlyRptField;
    
    /// <remarks/>
    public SettlementFailsMonthlyReportV01 SttlmFlsMnthlyRpt {
        get {
            return this.sttlmFlsMnthlyRptField;
        }
        set {
            this.sttlmFlsMnthlyRptField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsMonthlyReportV01 {
    
    private SettlementFailsReportHeader2 rptHdrField;
    
    private SettlementFailsData3 mnthlyAggtField;
    
    private SettlementFailsDailyData3[] dalyDataField;
    
    private SupplementaryData1[] splmtryDataField;
    
    /// <remarks/>
    public SettlementFailsReportHeader2 RptHdr {
        get {
            return this.rptHdrField;
        }
        set {
            this.rptHdrField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsData3 MnthlyAggt {
        get {
            return this.mnthlyAggtField;
        }
        set {
            this.mnthlyAggtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DalyData")]
    public SettlementFailsDailyData3[] DalyData {
        get {
            return this.dalyDataField;
        }
        set {
            this.dalyDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
    public SupplementaryData1[] SplmtryData {
        get {
            return this.splmtryDataField;
        }
        set {
            this.splmtryDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsReportHeader2 {
    
    private System.DateTime creDtTmField;
    
    private DatePeriod2 rptgPrdField;
    
    private string ccyField;
    
    private TransactionOperationType4Code rptStsField;
    
    private SecuritiesSettlementSystemIdentification2 sctiesSttlmSysField;
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
    
    /// <remarks/>
    public DatePeriod2 RptgPrd {
        get {
            return this.rptgPrdField;
        }
        set {
            this.rptgPrdField = value;
        }
    }
    
    /// <remarks/>
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    public TransactionOperationType4Code RptSts {
        get {
            return this.rptStsField;
        }
        set {
            this.rptStsField = value;
        }
    }
    
    /// <remarks/>
    public SecuritiesSettlementSystemIdentification2 SctiesSttlmSys {
        get {
            return this.sctiesSttlmSysField;
        }
        set {
            this.sctiesSttlmSysField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class DatePeriod2 {
    
    private System.DateTime frDtField;
    
    private System.DateTime toDtField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FrDt {
        get {
            return this.frDtField;
        }
        set {
            this.frDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ToDt {
        get {
            return this.toDtField;
        }
        set {
            this.toDtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SupplementaryData1 {
    
    private string plcAndNmField;
    
    private System.Xml.XmlElement envlpField;
    
    /// <remarks/>
    public string PlcAndNm {
        get {
            return this.plcAndNmField;
        }
        set {
            this.plcAndNmField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Envlp {
        get {
            return this.envlpField;
        }
        set {
            this.envlpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementDailyFailureReason3 {
    
    private SettlementTotalData1Choice faildSctiesField;
    
    private SettlementTotalData1Choice faildCshField;
    
    /// <remarks/>
    public SettlementTotalData1Choice FaildScties {
        get {
            return this.faildSctiesField;
        }
        set {
            this.faildSctiesField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice FaildCsh {
        get {
            return this.faildCshField;
        }
        set {
            this.faildCshField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementTotalData1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data", typeof(SettlementTotalData1))]
    [System.Xml.Serialization.XmlElementAttribute("DataSetActn", typeof(ReportPeriodActivity1Code))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementTotalData1 {
    
    private SettlementDataVolume2 sttldField;
    
    private SettlementDataVolume2 faildField;
    
    private SettlementDataVolume2 ttlField;
    
    private SettlementDataRate2 faildRateField;
    
    /// <remarks/>
    public SettlementDataVolume2 Sttld {
        get {
            return this.sttldField;
        }
        set {
            this.sttldField = value;
        }
    }
    
    /// <remarks/>
    public SettlementDataVolume2 Faild {
        get {
            return this.faildField;
        }
        set {
            this.faildField = value;
        }
    }
    
    /// <remarks/>
    public SettlementDataVolume2 Ttl {
        get {
            return this.ttlField;
        }
        set {
            this.ttlField = value;
        }
    }
    
    /// <remarks/>
    public SettlementDataRate2 FaildRate {
        get {
            return this.faildRateField;
        }
        set {
            this.faildRateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementDataVolume2 {
    
    private decimal volField;
    
    private decimal valField;
    
    /// <remarks/>
    public decimal Vol {
        get {
            return this.volField;
        }
        set {
            this.volField = value;
        }
    }
    
    /// <remarks/>
    public decimal Val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementDataRate2 {
    
    private decimal volField;
    
    private decimal valField;
    
    /// <remarks/>
    public decimal Vol {
        get {
            return this.volField;
        }
        set {
            this.volField = value;
        }
    }
    
    /// <remarks/>
    public decimal Val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public enum ReportPeriodActivity1Code {
    
    /// <remarks/>
    NOTX,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementDailyFailureReason1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data", typeof(SettlementDailyFailureReason3))]
    [System.Xml.Serialization.XmlElementAttribute("DataSetActn", typeof(ReportPeriodActivity1Code))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsDailyInstructionType3 {
    
    private SettlementDailyFailureReason1Choice dlvryVrssPmtField;
    
    private SettlementDailyFailureReason1Choice dlvryWthPmtField;
    
    private SettlementDailyFailureReason1Choice pmtFreeOfDlvryField;
    
    private SettlementDailyFailureReason1Choice freeOfPmtField;
    
    /// <remarks/>
    public SettlementDailyFailureReason1Choice DlvryVrssPmt {
        get {
            return this.dlvryVrssPmtField;
        }
        set {
            this.dlvryVrssPmtField = value;
        }
    }
    
    /// <remarks/>
    public SettlementDailyFailureReason1Choice DlvryWthPmt {
        get {
            return this.dlvryWthPmtField;
        }
        set {
            this.dlvryWthPmtField = value;
        }
    }
    
    /// <remarks/>
    public SettlementDailyFailureReason1Choice PmtFreeOfDlvry {
        get {
            return this.pmtFreeOfDlvryField;
        }
        set {
            this.pmtFreeOfDlvryField = value;
        }
    }
    
    /// <remarks/>
    public SettlementDailyFailureReason1Choice FreeOfPmt {
        get {
            return this.freeOfPmtField;
        }
        set {
            this.freeOfPmtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsDailyInstructionType1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data", typeof(SettlementFailsDailyInstructionType3))]
    [System.Xml.Serialization.XmlElementAttribute("DataSetActn", typeof(ReportPeriodActivity1Code))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsDailyCSD3 {
    
    private SettlementFailsDailyInstructionType1Choice intraCSDField;
    
    private SettlementFailsDailyInstructionType1Choice crossCSDField;
    
    /// <remarks/>
    public SettlementFailsDailyInstructionType1Choice IntraCSD {
        get {
            return this.intraCSDField;
        }
        set {
            this.intraCSDField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyInstructionType1Choice CrossCSD {
        get {
            return this.crossCSDField;
        }
        set {
            this.crossCSDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsDailyCSD1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data", typeof(SettlementFailsDailyCSD3))]
    [System.Xml.Serialization.XmlElementAttribute("DataSetActn", typeof(ReportPeriodActivity1Code))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsDailyTransactionType3 {
    
    private SettlementFailsDailyCSD1Choice sctiesBuyOrSellField;
    
    private SettlementFailsDailyCSD1Choice collMgmtOprField;
    
    private SettlementFailsDailyCSD1Choice sctiesLndgOrBrrwgField;
    
    private SettlementFailsDailyCSD1Choice rpAgrmtField;
    
    private SettlementFailsDailyCSD1Choice othrField;
    
    /// <remarks/>
    public SettlementFailsDailyCSD1Choice SctiesBuyOrSell {
        get {
            return this.sctiesBuyOrSellField;
        }
        set {
            this.sctiesBuyOrSellField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyCSD1Choice CollMgmtOpr {
        get {
            return this.collMgmtOprField;
        }
        set {
            this.collMgmtOprField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyCSD1Choice SctiesLndgOrBrrwg {
        get {
            return this.sctiesLndgOrBrrwgField;
        }
        set {
            this.sctiesLndgOrBrrwgField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyCSD1Choice RpAgrmt {
        get {
            return this.rpAgrmtField;
        }
        set {
            this.rpAgrmtField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyCSD1Choice Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsDailyTransactionType1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data", typeof(SettlementFailsDailyTransactionType3))]
    [System.Xml.Serialization.XmlElementAttribute("DataSetActn", typeof(ReportPeriodActivity1Code))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsDailyInstrument3 {
    
    private SettlementFailsDailyTransactionType1Choice eqtyField;
    
    private SettlementFailsDailyTransactionType1Choice svrgnDebtField;
    
    private SettlementFailsDailyTransactionType1Choice bdField;
    
    private SettlementFailsDailyTransactionType1Choice othrTrfblSctiesField;
    
    private SettlementFailsDailyTransactionType1Choice xchgTraddFndsField;
    
    private SettlementFailsDailyTransactionType1Choice cllctvInvstmtUdrtkgsField;
    
    private SettlementFailsDailyTransactionType1Choice mnyMktInstrmField;
    
    private SettlementFailsDailyTransactionType1Choice emssnAllwncField;
    
    private SettlementFailsDailyTransactionType1Choice othrField;
    
    /// <remarks/>
    public SettlementFailsDailyTransactionType1Choice Eqty {
        get {
            return this.eqtyField;
        }
        set {
            this.eqtyField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyTransactionType1Choice SvrgnDebt {
        get {
            return this.svrgnDebtField;
        }
        set {
            this.svrgnDebtField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyTransactionType1Choice Bd {
        get {
            return this.bdField;
        }
        set {
            this.bdField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyTransactionType1Choice OthrTrfblScties {
        get {
            return this.othrTrfblSctiesField;
        }
        set {
            this.othrTrfblSctiesField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyTransactionType1Choice XchgTraddFnds {
        get {
            return this.xchgTraddFndsField;
        }
        set {
            this.xchgTraddFndsField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyTransactionType1Choice CllctvInvstmtUdrtkgs {
        get {
            return this.cllctvInvstmtUdrtkgsField;
        }
        set {
            this.cllctvInvstmtUdrtkgsField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyTransactionType1Choice MnyMktInstrm {
        get {
            return this.mnyMktInstrmField;
        }
        set {
            this.mnyMktInstrmField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyTransactionType1Choice EmssnAllwnc {
        get {
            return this.emssnAllwncField;
        }
        set {
            this.emssnAllwncField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyTransactionType1Choice Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsDailyData3 {
    
    private System.DateTime rptgDtField;
    
    private SettlementFailsDailyInstrument3 dalyRcrdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime RptgDt {
        get {
            return this.rptgDtField;
        }
        set {
            this.rptgDtField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsDailyInstrument3 DalyRcrd {
        get {
            return this.dalyRcrdField;
        }
        set {
            this.dalyRcrdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailureReason2 {
    
    private string mainRsnsField;
    
    private string effcncyImprvmtField;
    
    /// <remarks/>
    public string MainRsns {
        get {
            return this.mainRsnsField;
        }
        set {
            this.mainRsnsField = value;
        }
    }
    
    /// <remarks/>
    public string EffcncyImprvmt {
        get {
            return this.effcncyImprvmtField;
        }
        set {
            this.effcncyImprvmtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailureReason3 {
    
    private decimal avrgDrtnField;
    
    private bool avrgDrtnFieldSpecified;
    
    private SettlementFailureReason2[] descField;
    
    /// <remarks/>
    public decimal AvrgDrtn {
        get {
            return this.avrgDrtnField;
        }
        set {
            this.avrgDrtnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AvrgDrtnSpecified {
        get {
            return this.avrgDrtnFieldSpecified;
        }
        set {
            this.avrgDrtnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Desc")]
    public SettlementFailureReason2[] Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsTransactionType2 {
    
    private SettlementTotalData1Choice sctiesBuyOrSellField;
    
    private SettlementTotalData1Choice collMgmtOprField;
    
    private SettlementTotalData1Choice sctiesLndgOrBrrwgField;
    
    private SettlementTotalData1Choice rpAgrmtField;
    
    private SettlementTotalData1Choice othrField;
    
    /// <remarks/>
    public SettlementTotalData1Choice SctiesBuyOrSell {
        get {
            return this.sctiesBuyOrSellField;
        }
        set {
            this.sctiesBuyOrSellField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice CollMgmtOpr {
        get {
            return this.collMgmtOprField;
        }
        set {
            this.collMgmtOprField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice SctiesLndgOrBrrwg {
        get {
            return this.sctiesLndgOrBrrwgField;
        }
        set {
            this.sctiesLndgOrBrrwgField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice RpAgrmt {
        get {
            return this.rpAgrmtField;
        }
        set {
            this.rpAgrmtField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class IdentificationSource3Choice {
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class OtherIdentification1 {
    
    private string idField;
    
    private string sfxField;
    
    private IdentificationSource3Choice tpField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Sfx {
        get {
            return this.sfxField;
        }
        set {
            this.sfxField = value;
        }
    }
    
    /// <remarks/>
    public IdentificationSource3Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SecurityIdentification19 {
    
    private string iSINField;
    
    private OtherIdentification1[] othrIdField;
    
    private string descField;
    
    /// <remarks/>
    public string ISIN {
        get {
            return this.iSINField;
        }
        set {
            this.iSINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OthrId")]
    public OtherIdentification1[] OthrId {
        get {
            return this.othrIdField;
        }
        set {
            this.othrIdField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsSecurities1 {
    
    private SecurityIdentification19 finInstrmIdField;
    
    private string rankField;
    
    /// <remarks/>
    public SecurityIdentification19 FinInstrmId {
        get {
            return this.finInstrmIdField;
        }
        set {
            this.finInstrmIdField = value;
        }
    }
    
    /// <remarks/>
    public string Rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsSecuritiesRange1 {
    
    private SettlementFailsSecurities1[] hghstInVolField;
    
    private SettlementFailsSecurities1[] hghstInValField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HghstInVol")]
    public SettlementFailsSecurities1[] HghstInVol {
        get {
            return this.hghstInVolField;
        }
        set {
            this.hghstInVolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HghstInVal")]
    public SettlementFailsSecurities1[] HghstInVal {
        get {
            return this.hghstInValField;
        }
        set {
            this.hghstInValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsInstrument2 {
    
    private SettlementTotalData1Choice eqtyField;
    
    private SettlementTotalData1Choice svrgnDebtField;
    
    private SettlementTotalData1Choice bdField;
    
    private SettlementTotalData1Choice othrTrfblSctiesField;
    
    private SettlementTotalData1Choice xchgTraddFndsField;
    
    private SettlementTotalData1Choice cllctvInvstmtUdrtkgsField;
    
    private SettlementTotalData1Choice mnyMktInstrmField;
    
    private SettlementTotalData1Choice emssnAllwncField;
    
    private SettlementTotalData1Choice othrField;
    
    /// <remarks/>
    public SettlementTotalData1Choice Eqty {
        get {
            return this.eqtyField;
        }
        set {
            this.eqtyField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice SvrgnDebt {
        get {
            return this.svrgnDebtField;
        }
        set {
            this.svrgnDebtField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice Bd {
        get {
            return this.bdField;
        }
        set {
            this.bdField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice OthrTrfblScties {
        get {
            return this.othrTrfblSctiesField;
        }
        set {
            this.othrTrfblSctiesField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice XchgTraddFnds {
        get {
            return this.xchgTraddFndsField;
        }
        set {
            this.xchgTraddFndsField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice CllctvInvstmtUdrtkgs {
        get {
            return this.cllctvInvstmtUdrtkgsField;
        }
        set {
            this.cllctvInvstmtUdrtkgsField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice MnyMktInstrm {
        get {
            return this.mnyMktInstrmField;
        }
        set {
            this.mnyMktInstrmField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice EmssnAllwnc {
        get {
            return this.emssnAllwncField;
        }
        set {
            this.emssnAllwncField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1Choice Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsCurrency2 {
    
    private string ccyField;
    
    private SettlementTotalData1 dataField;
    
    /// <remarks/>
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1 Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsParticipant1 {
    
    private string lEIField;
    
    private string rankField;
    
    private SettlementTotalData1 aggtField;
    
    /// <remarks/>
    public string LEI {
        get {
            return this.lEIField;
        }
        set {
            this.lEIField = value;
        }
    }
    
    /// <remarks/>
    public string Rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTotalData1 Aggt {
        get {
            return this.aggtField;
        }
        set {
            this.aggtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsParticipantRange1 {
    
    private SettlementFailsParticipant1[] hghstInVolField;
    
    private SettlementFailsParticipant1[] hghstInValField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HghstInVol")]
    public SettlementFailsParticipant1[] HghstInVol {
        get {
            return this.hghstInVolField;
        }
        set {
            this.hghstInVolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HghstInVal")]
    public SettlementFailsParticipant1[] HghstInVal {
        get {
            return this.hghstInValField;
        }
        set {
            this.hghstInValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SettlementFailsData3 {
    
    private SettlementTotalData1 ttlField;
    
    private SettlementFailsParticipantRange1 ptcptInFailField;
    
    private SettlementFailsCurrency2[] flsPerCcyField;
    
    private SettlementFailsInstrument2 flsPerFinInstrmTpField;
    
    private SettlementFailsSecuritiesRange1 sctiesInFailField;
    
    private SettlementFailsTransactionType2 flsPerTxTpField;
    
    private SettlementDataVolume2 ttlSttlmPnltiesField;
    
    private SettlementFailureReason3 failrRsnField;
    
    /// <remarks/>
    public SettlementTotalData1 Ttl {
        get {
            return this.ttlField;
        }
        set {
            this.ttlField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsParticipantRange1 PtcptInFail {
        get {
            return this.ptcptInFailField;
        }
        set {
            this.ptcptInFailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FlsPerCcy")]
    public SettlementFailsCurrency2[] FlsPerCcy {
        get {
            return this.flsPerCcyField;
        }
        set {
            this.flsPerCcyField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsInstrument2 FlsPerFinInstrmTp {
        get {
            return this.flsPerFinInstrmTpField;
        }
        set {
            this.flsPerFinInstrmTpField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsSecuritiesRange1 SctiesInFail {
        get {
            return this.sctiesInFailField;
        }
        set {
            this.sctiesInFailField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailsTransactionType2 FlsPerTxTp {
        get {
            return this.flsPerTxTpField;
        }
        set {
            this.flsPerTxTpField = value;
        }
    }
    
    /// <remarks/>
    public SettlementDataVolume2 TtlSttlmPnlties {
        get {
            return this.ttlSttlmPnltiesField;
        }
        set {
            this.ttlSttlmPnltiesField = value;
        }
    }
    
    /// <remarks/>
    public SettlementFailureReason3 FailrRsn {
        get {
            return this.failrRsnField;
        }
        set {
            this.failrRsnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class Contact9 {
    
    private string nmField;
    
    private string phneNbField;
    
    private string emailAdrField;
    
    private string fctnField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public string PhneNb {
        get {
            return this.phneNbField;
        }
        set {
            this.phneNbField = value;
        }
    }
    
    /// <remarks/>
    public string EmailAdr {
        get {
            return this.emailAdrField;
        }
        set {
            this.emailAdrField = value;
        }
    }
    
    /// <remarks/>
    public string Fctn {
        get {
            return this.fctnField;
        }
        set {
            this.fctnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public partial class SecuritiesSettlementSystemIdentification2 {
    
    private string sysIdField;
    
    private string sysNmField;
    
    private string ctryOfJursdctnField;
    
    private string cSDLglNmField;
    
    private string lEIField;
    
    private Contact9[] rspnsblPtyField;
    
    /// <remarks/>
    public string SysId {
        get {
            return this.sysIdField;
        }
        set {
            this.sysIdField = value;
        }
    }
    
    /// <remarks/>
    public string SysNm {
        get {
            return this.sysNmField;
        }
        set {
            this.sysNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtryOfJursdctn {
        get {
            return this.ctryOfJursdctnField;
        }
        set {
            this.ctryOfJursdctnField = value;
        }
    }
    
    /// <remarks/>
    public string CSDLglNm {
        get {
            return this.cSDLglNmField;
        }
        set {
            this.cSDLglNmField = value;
        }
    }
    
    /// <remarks/>
    public string LEI {
        get {
            return this.lEIField;
        }
        set {
            this.lEIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RspnsblPty")]
    public Contact9[] RspnsblPty {
        get {
            return this.rspnsblPtyField;
        }
        set {
            this.rspnsblPtyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.100.001.01")]
public enum TransactionOperationType4Code {
    
    /// <remarks/>
    NEWT,
    
    /// <remarks/>
    AMND,
    
    /// <remarks/>
    CANC,
}
