//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03", IsNullable=false)]
public partial class Document {
    
    private DeltaReportV03 dltaRptField;
    
    /// <remarks/>
    public DeltaReportV03 DltaRpt {
        get {
            return this.dltaRptField;
        }
        set {
            this.dltaRptField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class DeltaReportV03 {
    
    private MessageIdentification1 rptIdField;
    
    private SimpleIdentificationInformation txIdField;
    
    private DocumentIdentification3 estblishdBaselnIdField;
    
    private TransactionStatus4 txStsField;
    
    private Count1 amdmntNbField;
    
    private DocumentIdentification5[] usrTxRefField;
    
    private PartyIdentification26 buyrField;
    
    private PartyIdentification26 sellrField;
    
    private BICIdentification1 buyrBkField;
    
    private BICIdentification1 sellrBkField;
    
    private DocumentIdentification1 submitrPropsdBaselnRefField;
    
    private ComparisonResult2[] updtdElmtField;
    
    private PendingActivity2 reqForActnField;
    
    /// <remarks/>
    public MessageIdentification1 RptId {
        get {
            return this.rptIdField;
        }
        set {
            this.rptIdField = value;
        }
    }
    
    /// <remarks/>
    public SimpleIdentificationInformation TxId {
        get {
            return this.txIdField;
        }
        set {
            this.txIdField = value;
        }
    }
    
    /// <remarks/>
    public DocumentIdentification3 EstblishdBaselnId {
        get {
            return this.estblishdBaselnIdField;
        }
        set {
            this.estblishdBaselnIdField = value;
        }
    }
    
    /// <remarks/>
    public TransactionStatus4 TxSts {
        get {
            return this.txStsField;
        }
        set {
            this.txStsField = value;
        }
    }
    
    /// <remarks/>
    public Count1 AmdmntNb {
        get {
            return this.amdmntNbField;
        }
        set {
            this.amdmntNbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsrTxRef")]
    public DocumentIdentification5[] UsrTxRef {
        get {
            return this.usrTxRefField;
        }
        set {
            this.usrTxRefField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification26 Buyr {
        get {
            return this.buyrField;
        }
        set {
            this.buyrField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification26 Sellr {
        get {
            return this.sellrField;
        }
        set {
            this.sellrField = value;
        }
    }
    
    /// <remarks/>
    public BICIdentification1 BuyrBk {
        get {
            return this.buyrBkField;
        }
        set {
            this.buyrBkField = value;
        }
    }
    
    /// <remarks/>
    public BICIdentification1 SellrBk {
        get {
            return this.sellrBkField;
        }
        set {
            this.sellrBkField = value;
        }
    }
    
    /// <remarks/>
    public DocumentIdentification1 SubmitrPropsdBaselnRef {
        get {
            return this.submitrPropsdBaselnRefField;
        }
        set {
            this.submitrPropsdBaselnRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UpdtdElmt")]
    public ComparisonResult2[] UpdtdElmt {
        get {
            return this.updtdElmtField;
        }
        set {
            this.updtdElmtField = value;
        }
    }
    
    /// <remarks/>
    public PendingActivity2 ReqForActn {
        get {
            return this.reqForActnField;
        }
        set {
            this.reqForActnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class MessageIdentification1 {
    
    private string idField;
    
    private System.DateTime creDtTmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class PendingActivity2 {
    
    private Action2Code tpField;
    
    private string descField;
    
    /// <remarks/>
    public Action2Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public enum Action2Code {
    
    /// <remarks/>
    SBTW,
    
    /// <remarks/>
    RSTW,
    
    /// <remarks/>
    RSBS,
    
    /// <remarks/>
    ARDM,
    
    /// <remarks/>
    ARCS,
    
    /// <remarks/>
    ARES,
    
    /// <remarks/>
    WAIT,
    
    /// <remarks/>
    UPDT,
    
    /// <remarks/>
    SBDS,
    
    /// <remarks/>
    ARBA,
    
    /// <remarks/>
    ARRO,
    
    /// <remarks/>
    CINR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class Addition2 {
    
    private string propsdValField;
    
    /// <remarks/>
    public string PropsdVal {
        get {
            return this.propsdValField;
        }
        set {
            this.propsdValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class Deletion2 {
    
    private string deltdValField;
    
    /// <remarks/>
    public string DeltdVal {
        get {
            return this.deltdValField;
        }
        set {
            this.deltdValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class Replacement2 {
    
    private string curValField;
    
    private string propsdValField;
    
    /// <remarks/>
    public string CurVal {
        get {
            return this.curValField;
        }
        set {
            this.curValField = value;
        }
    }
    
    /// <remarks/>
    public string PropsdVal {
        get {
            return this.propsdValField;
        }
        set {
            this.propsdValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class ComparisonResult2 {
    
    private decimal elmtSeqNbField;
    
    private string elmtPthField;
    
    private string elmtNmField;
    
    private object itemField;
    
    /// <remarks/>
    public decimal ElmtSeqNb {
        get {
            return this.elmtSeqNbField;
        }
        set {
            this.elmtSeqNbField = value;
        }
    }
    
    /// <remarks/>
    public string ElmtPth {
        get {
            return this.elmtPthField;
        }
        set {
            this.elmtPthField = value;
        }
    }
    
    /// <remarks/>
    public string ElmtNm {
        get {
            return this.elmtNmField;
        }
        set {
            this.elmtNmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Addtn", typeof(Addition2))]
    [System.Xml.Serialization.XmlElementAttribute("Deltn", typeof(Deletion2))]
    [System.Xml.Serialization.XmlElementAttribute("Rplcmnt", typeof(Replacement2))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class DocumentIdentification1 {
    
    private string idField;
    
    private decimal vrsnField;
    
    private BICIdentification1 submitrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
    
    /// <remarks/>
    public BICIdentification1 Submitr {
        get {
            return this.submitrField;
        }
        set {
            this.submitrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class BICIdentification1 {
    
    private string bICField;
    
    /// <remarks/>
    public string BIC {
        get {
            return this.bICField;
        }
        set {
            this.bICField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class PostalAddress5 {
    
    private string strtNmField;
    
    private string pstCdIdField;
    
    private string twnNmField;
    
    private string ctrySubDvsnField;
    
    private string ctryField;
    
    /// <remarks/>
    public string StrtNm {
        get {
            return this.strtNmField;
        }
        set {
            this.strtNmField = value;
        }
    }
    
    /// <remarks/>
    public string PstCdId {
        get {
            return this.pstCdIdField;
        }
        set {
            this.pstCdIdField = value;
        }
    }
    
    /// <remarks/>
    public string TwnNm {
        get {
            return this.twnNmField;
        }
        set {
            this.twnNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsn {
        get {
            return this.ctrySubDvsnField;
        }
        set {
            this.ctrySubDvsnField = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class GenericIdentification4 {
    
    private string idField;
    
    private string idTpField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string IdTp {
        get {
            return this.idTpField;
        }
        set {
            this.idTpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class PartyIdentification26 {
    
    private string nmField;
    
    private GenericIdentification4 prtryIdField;
    
    private PostalAddress5 pstlAdrField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification4 PrtryId {
        get {
            return this.prtryIdField;
        }
        set {
            this.prtryIdField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress5 PstlAdr {
        get {
            return this.pstlAdrField;
        }
        set {
            this.pstlAdrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class DocumentIdentification5 {
    
    private string idField;
    
    private BICIdentification1 idIssrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public BICIdentification1 IdIssr {
        get {
            return this.idIssrField;
        }
        set {
            this.idIssrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class Count1 {
    
    private decimal nbField;
    
    /// <remarks/>
    public decimal Nb {
        get {
            return this.nbField;
        }
        set {
            this.nbField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class TransactionStatus4 {
    
    private BaselineStatus3Code stsField;
    
    /// <remarks/>
    public BaselineStatus3Code Sts {
        get {
            return this.stsField;
        }
        set {
            this.stsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public enum BaselineStatus3Code {
    
    /// <remarks/>
    PROP,
    
    /// <remarks/>
    CLSD,
    
    /// <remarks/>
    PMTC,
    
    /// <remarks/>
    ESTD,
    
    /// <remarks/>
    ACTV,
    
    /// <remarks/>
    COMP,
    
    /// <remarks/>
    AMRQ,
    
    /// <remarks/>
    RARQ,
    
    /// <remarks/>
    CLRQ,
    
    /// <remarks/>
    SCRQ,
    
    /// <remarks/>
    SERQ,
    
    /// <remarks/>
    DARQ,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class DocumentIdentification3 {
    
    private string idField;
    
    private decimal vrsnField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.015.001.03")]
public partial class SimpleIdentificationInformation {
    
    private string idField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
