//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03", IsNullable=false)]
public partial class Document {
    
    private TransactionReportRequestV03 txRptReqField;
    
    /// <remarks/>
    public TransactionReportRequestV03 TxRptReq {
        get {
            return this.txRptReqField;
        }
        set {
            this.txRptReqField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
public partial class TransactionReportRequestV03 {
    
    private MessageIdentification1 reqIdField;
    
    private ReportSpecification4 rptSpcfctnField;
    
    /// <remarks/>
    public MessageIdentification1 ReqId {
        get {
            return this.reqIdField;
        }
        set {
            this.reqIdField = value;
        }
    }
    
    /// <remarks/>
    public ReportSpecification4 RptSpcfctn {
        get {
            return this.rptSpcfctnField;
        }
        set {
            this.rptSpcfctnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
public partial class MessageIdentification1 {
    
    private string idField;
    
    private System.DateTime creDtTmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
public partial class PendingActivity1 {
    
    private Action1Code tpField;
    
    private string descField;
    
    /// <remarks/>
    public Action1Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
public enum Action1Code {
    
    /// <remarks/>
    SBTW,
    
    /// <remarks/>
    RSTW,
    
    /// <remarks/>
    RSBS,
    
    /// <remarks/>
    ARDM,
    
    /// <remarks/>
    ARCS,
    
    /// <remarks/>
    ARES,
    
    /// <remarks/>
    WAIT,
    
    /// <remarks/>
    UPDT,
    
    /// <remarks/>
    SBDS,
    
    /// <remarks/>
    ARBA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
public partial class GenericIdentification4 {
    
    private string idField;
    
    private string idTpField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string IdTp {
        get {
            return this.idTpField;
        }
        set {
            this.idTpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
public partial class PartyIdentification28 {
    
    private string nmField;
    
    private GenericIdentification4 prtryIdField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification4 PrtryId {
        get {
            return this.prtryIdField;
        }
        set {
            this.prtryIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
public partial class BICIdentification1 {
    
    private string bICField;
    
    /// <remarks/>
    public string BIC {
        get {
            return this.bICField;
        }
        set {
            this.bICField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
public partial class TransactionStatus4 {
    
    private BaselineStatus3Code stsField;
    
    /// <remarks/>
    public BaselineStatus3Code Sts {
        get {
            return this.stsField;
        }
        set {
            this.stsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
public enum BaselineStatus3Code {
    
    /// <remarks/>
    PROP,
    
    /// <remarks/>
    CLSD,
    
    /// <remarks/>
    PMTC,
    
    /// <remarks/>
    ESTD,
    
    /// <remarks/>
    ACTV,
    
    /// <remarks/>
    COMP,
    
    /// <remarks/>
    AMRQ,
    
    /// <remarks/>
    RARQ,
    
    /// <remarks/>
    CLRQ,
    
    /// <remarks/>
    SCRQ,
    
    /// <remarks/>
    SERQ,
    
    /// <remarks/>
    DARQ,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsmt.042.001.03")]
public partial class ReportSpecification4 {
    
    private string[] txIdField;
    
    private TransactionStatus4[] txStsField;
    
    private string[] submitrTxRefField;
    
    private BICIdentification1[] nttiesToBeRptdField;
    
    private BICIdentification1[] crspdtField;
    
    private BICIdentification1[] submitgBkField;
    
    private BICIdentification1[] oblgrBkField;
    
    private PartyIdentification28[] buyrField;
    
    private PartyIdentification28[] sellrField;
    
    private string[] buyrCtryField;
    
    private string[] sellrCtryField;
    
    private string[] crspdtCtryField;
    
    private PendingActivity1[] pdgReqForActnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TxId")]
    public string[] TxId {
        get {
            return this.txIdField;
        }
        set {
            this.txIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TxSts")]
    public TransactionStatus4[] TxSts {
        get {
            return this.txStsField;
        }
        set {
            this.txStsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubmitrTxRef")]
    public string[] SubmitrTxRef {
        get {
            return this.submitrTxRefField;
        }
        set {
            this.submitrTxRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NttiesToBeRptd")]
    public BICIdentification1[] NttiesToBeRptd {
        get {
            return this.nttiesToBeRptdField;
        }
        set {
            this.nttiesToBeRptdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Crspdt")]
    public BICIdentification1[] Crspdt {
        get {
            return this.crspdtField;
        }
        set {
            this.crspdtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubmitgBk")]
    public BICIdentification1[] SubmitgBk {
        get {
            return this.submitgBkField;
        }
        set {
            this.submitgBkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OblgrBk")]
    public BICIdentification1[] OblgrBk {
        get {
            return this.oblgrBkField;
        }
        set {
            this.oblgrBkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Buyr")]
    public PartyIdentification28[] Buyr {
        get {
            return this.buyrField;
        }
        set {
            this.buyrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Sellr")]
    public PartyIdentification28[] Sellr {
        get {
            return this.sellrField;
        }
        set {
            this.sellrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BuyrCtry")]
    public string[] BuyrCtry {
        get {
            return this.buyrCtryField;
        }
        set {
            this.buyrCtryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellrCtry")]
    public string[] SellrCtry {
        get {
            return this.sellrCtryField;
        }
        set {
            this.sellrCtryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CrspdtCtry")]
    public string[] CrspdtCtry {
        get {
            return this.crspdtCtryField;
        }
        set {
            this.crspdtCtryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PdgReqForActn")]
    public PendingActivity1[] PdgReqForActn {
        get {
            return this.pdgReqForActnField;
        }
        set {
            this.pdgReqForActnField = value;
        }
    }
}
