//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03", IsNullable=false)]
public partial class Document {
    
    private CertificateManagementResponseV03 certMgmtRspnField;
    
    /// <remarks/>
    public CertificateManagementResponseV03 CertMgmtRspn {
        get {
            return this.certMgmtRspnField;
        }
        set {
            this.certMgmtRspnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class CertificateManagementResponseV03 {
    
    private TMSHeader1 hdrField;
    
    private CertificateManagementResponse2 certMgmtRspnField;
    
    private ContentInformationType21 sctyTrlrField;
    
    /// <remarks/>
    public TMSHeader1 Hdr {
        get {
            return this.hdrField;
        }
        set {
            this.hdrField = value;
        }
    }
    
    /// <remarks/>
    public CertificateManagementResponse2 CertMgmtRspn {
        get {
            return this.certMgmtRspnField;
        }
        set {
            this.certMgmtRspnField = value;
        }
    }
    
    /// <remarks/>
    public ContentInformationType21 SctyTrlr {
        get {
            return this.sctyTrlrField;
        }
        set {
            this.sctyTrlrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class TMSHeader1 {
    
    private bool dwnldTrfField;
    
    private string frmtVrsnField;
    
    private decimal xchgIdField;
    
    private System.DateTime creDtTmField;
    
    private GenericIdentification176 initgPtyField;
    
    private GenericIdentification177 rcptPtyField;
    
    private Traceability8[] tracbltField;
    
    /// <remarks/>
    public bool DwnldTrf {
        get {
            return this.dwnldTrfField;
        }
        set {
            this.dwnldTrfField = value;
        }
    }
    
    /// <remarks/>
    public string FrmtVrsn {
        get {
            return this.frmtVrsnField;
        }
        set {
            this.frmtVrsnField = value;
        }
    }
    
    /// <remarks/>
    public decimal XchgId {
        get {
            return this.xchgIdField;
        }
        set {
            this.xchgIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification176 InitgPty {
        get {
            return this.initgPtyField;
        }
        set {
            this.initgPtyField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification177 RcptPty {
        get {
            return this.rcptPtyField;
        }
        set {
            this.rcptPtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tracblt")]
    public Traceability8[] Tracblt {
        get {
            return this.tracbltField;
        }
        set {
            this.tracbltField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class GenericIdentification176 {
    
    private string idField;
    
    private PartyType33Code tpField;
    
    private bool tpFieldSpecified;
    
    private PartyType33Code issrField;
    
    private bool issrFieldSpecified;
    
    private string ctryField;
    
    private string shrtNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public PartyType33Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TpSpecified {
        get {
            return this.tpFieldSpecified;
        }
        set {
            this.tpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PartyType33Code Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IssrSpecified {
        get {
            return this.issrFieldSpecified;
        }
        set {
            this.issrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    public string ShrtNm {
        get {
            return this.shrtNmField;
        }
        set {
            this.shrtNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum PartyType33Code {
    
    /// <remarks/>
    OPOI,
    
    /// <remarks/>
    MERC,
    
    /// <remarks/>
    ACCP,
    
    /// <remarks/>
    ITAG,
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    CISS,
    
    /// <remarks/>
    DLIS,
    
    /// <remarks/>
    MTMG,
    
    /// <remarks/>
    TAXH,
    
    /// <remarks/>
    TMGT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Parameter5 {
    
    private Algorithm11Code dgstAlgoField;
    
    private bool dgstAlgoFieldSpecified;
    
    /// <remarks/>
    public Algorithm11Code DgstAlgo {
        get {
            return this.dgstAlgoField;
        }
        set {
            this.dgstAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DgstAlgoSpecified {
        get {
            return this.dgstAlgoFieldSpecified;
        }
        set {
            this.dgstAlgoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum Algorithm11Code {
    
    /// <remarks/>
    HS25,
    
    /// <remarks/>
    HS38,
    
    /// <remarks/>
    HS51,
    
    /// <remarks/>
    HS01,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class AlgorithmIdentification12 {
    
    private Algorithm8Code algoField;
    
    private Parameter5 paramField;
    
    /// <remarks/>
    public Algorithm8Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter5 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum Algorithm8Code {
    
    /// <remarks/>
    MGF1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Parameter11 {
    
    private Algorithm16Code dgstAlgoField;
    
    private AlgorithmIdentification12 mskGnrtrAlgoField;
    
    private decimal saltLngthField;
    
    private decimal trlrFldField;
    
    private bool trlrFldFieldSpecified;
    
    /// <remarks/>
    public Algorithm16Code DgstAlgo {
        get {
            return this.dgstAlgoField;
        }
        set {
            this.dgstAlgoField = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification12 MskGnrtrAlgo {
        get {
            return this.mskGnrtrAlgoField;
        }
        set {
            this.mskGnrtrAlgoField = value;
        }
    }
    
    /// <remarks/>
    public decimal SaltLngth {
        get {
            return this.saltLngthField;
        }
        set {
            this.saltLngthField = value;
        }
    }
    
    /// <remarks/>
    public decimal TrlrFld {
        get {
            return this.trlrFldField;
        }
        set {
            this.trlrFldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TrlrFldSpecified {
        get {
            return this.trlrFldFieldSpecified;
        }
        set {
            this.trlrFldFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum Algorithm16Code {
    
    /// <remarks/>
    HS25,
    
    /// <remarks/>
    HS38,
    
    /// <remarks/>
    HS51,
    
    /// <remarks/>
    HS01,
    
    /// <remarks/>
    SH31,
    
    /// <remarks/>
    SH32,
    
    /// <remarks/>
    SH33,
    
    /// <remarks/>
    SH35,
    
    /// <remarks/>
    SHK1,
    
    /// <remarks/>
    SHK2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class AlgorithmIdentification20 {
    
    private Algorithm19Code algoField;
    
    private Parameter11 paramField;
    
    /// <remarks/>
    public Algorithm19Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter11 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum Algorithm19Code {
    
    /// <remarks/>
    ERS2,
    
    /// <remarks/>
    ERS1,
    
    /// <remarks/>
    RPSS,
    
    /// <remarks/>
    ECC5,
    
    /// <remarks/>
    ECC1,
    
    /// <remarks/>
    ECC4,
    
    /// <remarks/>
    ECC2,
    
    /// <remarks/>
    ECC3,
    
    /// <remarks/>
    ERS3,
    
    /// <remarks/>
    ECP2,
    
    /// <remarks/>
    ECP3,
    
    /// <remarks/>
    ECP5,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class GenericInformation1 {
    
    private string nmField;
    
    private string valField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public string Val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Signer4 {
    
    private decimal vrsnField;
    
    private bool vrsnFieldSpecified;
    
    private Recipient5Choice sgnrIdField;
    
    private AlgorithmIdentification21 dgstAlgoField;
    
    private GenericInformation1[] sgndAttrbtsField;
    
    private AlgorithmIdentification20 sgntrAlgoField;
    
    private byte[] sgntrField;
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrsnSpecified {
        get {
            return this.vrsnFieldSpecified;
        }
        set {
            this.vrsnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Recipient5Choice SgnrId {
        get {
            return this.sgnrIdField;
        }
        set {
            this.sgnrIdField = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification21 DgstAlgo {
        get {
            return this.dgstAlgoField;
        }
        set {
            this.dgstAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SgndAttrbts")]
    public GenericInformation1[] SgndAttrbts {
        get {
            return this.sgndAttrbtsField;
        }
        set {
            this.sgndAttrbtsField = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification20 SgntrAlgo {
        get {
            return this.sgntrAlgoField;
        }
        set {
            this.sgntrAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Sgntr {
        get {
            return this.sgntrField;
        }
        set {
            this.sgntrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Recipient5Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IssrAndSrlNb", typeof(IssuerAndSerialNumber1))]
    [System.Xml.Serialization.XmlElementAttribute("KeyIdr", typeof(KEKIdentifier2))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class IssuerAndSerialNumber1 {
    
    private RelativeDistinguishedName1[] issrField;
    
    private byte[] srlNbField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("RltvDstngshdNm", IsNullable=false)]
    public RelativeDistinguishedName1[] Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] SrlNb {
        get {
            return this.srlNbField;
        }
        set {
            this.srlNbField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class RelativeDistinguishedName1 {
    
    private AttributeType1Code attrTpField;
    
    private string attrValField;
    
    /// <remarks/>
    public AttributeType1Code AttrTp {
        get {
            return this.attrTpField;
        }
        set {
            this.attrTpField = value;
        }
    }
    
    /// <remarks/>
    public string AttrVal {
        get {
            return this.attrValField;
        }
        set {
            this.attrValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum AttributeType1Code {
    
    /// <remarks/>
    CNAT,
    
    /// <remarks/>
    LATT,
    
    /// <remarks/>
    OATT,
    
    /// <remarks/>
    OUAT,
    
    /// <remarks/>
    CATT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class KEKIdentifier2 {
    
    private string keyIdField;
    
    private string keyVrsnField;
    
    private decimal seqNbField;
    
    private bool seqNbFieldSpecified;
    
    private byte[] derivtnIdField;
    
    /// <remarks/>
    public string KeyId {
        get {
            return this.keyIdField;
        }
        set {
            this.keyIdField = value;
        }
    }
    
    /// <remarks/>
    public string KeyVrsn {
        get {
            return this.keyVrsnField;
        }
        set {
            this.keyVrsnField = value;
        }
    }
    
    /// <remarks/>
    public decimal SeqNb {
        get {
            return this.seqNbField;
        }
        set {
            this.seqNbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SeqNbSpecified {
        get {
            return this.seqNbFieldSpecified;
        }
        set {
            this.seqNbFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] DerivtnId {
        get {
            return this.derivtnIdField;
        }
        set {
            this.derivtnIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class AlgorithmIdentification21 {
    
    private Algorithm16Code algoField;
    
    /// <remarks/>
    public Algorithm16Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class SignedData5 {
    
    private decimal vrsnField;
    
    private bool vrsnFieldSpecified;
    
    private AlgorithmIdentification21[] dgstAlgoField;
    
    private EncapsulatedContent3 ncpsltdCnttField;
    
    private byte[][] certField;
    
    private Signer4[] sgnrField;
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrsnSpecified {
        get {
            return this.vrsnFieldSpecified;
        }
        set {
            this.vrsnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DgstAlgo")]
    public AlgorithmIdentification21[] DgstAlgo {
        get {
            return this.dgstAlgoField;
        }
        set {
            this.dgstAlgoField = value;
        }
    }
    
    /// <remarks/>
    public EncapsulatedContent3 NcpsltdCntt {
        get {
            return this.ncpsltdCnttField;
        }
        set {
            this.ncpsltdCnttField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cert", DataType="base64Binary")]
    public byte[][] Cert {
        get {
            return this.certField;
        }
        set {
            this.certField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Sgnr")]
    public Signer4[] Sgnr {
        get {
            return this.sgnrField;
        }
        set {
            this.sgnrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class EncapsulatedContent3 {
    
    private ContentType2Code cnttTpField;
    
    private byte[] cnttField;
    
    /// <remarks/>
    public ContentType2Code CnttTp {
        get {
            return this.cnttTpField;
        }
        set {
            this.cnttTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Cntt {
        get {
            return this.cnttField;
        }
        set {
            this.cnttField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum ContentType2Code {
    
    /// <remarks/>
    DATA,
    
    /// <remarks/>
    SIGN,
    
    /// <remarks/>
    EVLP,
    
    /// <remarks/>
    DGST,
    
    /// <remarks/>
    AUTH,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Parameter7 {
    
    private byte[] initlstnVctrField;
    
    private BytePadding1Code bPddgField;
    
    private bool bPddgFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] InitlstnVctr {
        get {
            return this.initlstnVctrField;
        }
        set {
            this.initlstnVctrField = value;
        }
    }
    
    /// <remarks/>
    public BytePadding1Code BPddg {
        get {
            return this.bPddgField;
        }
        set {
            this.bPddgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BPddgSpecified {
        get {
            return this.bPddgFieldSpecified;
        }
        set {
            this.bPddgFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum BytePadding1Code {
    
    /// <remarks/>
    LNGT,
    
    /// <remarks/>
    NUL8,
    
    /// <remarks/>
    NULG,
    
    /// <remarks/>
    NULL,
    
    /// <remarks/>
    RAND,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class AlgorithmIdentification22 {
    
    private Algorithm17Code algoField;
    
    private Parameter7 paramField;
    
    /// <remarks/>
    public Algorithm17Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter7 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum Algorithm17Code {
    
    /// <remarks/>
    MACC,
    
    /// <remarks/>
    MCCS,
    
    /// <remarks/>
    CMA1,
    
    /// <remarks/>
    MCC1,
    
    /// <remarks/>
    CMA9,
    
    /// <remarks/>
    CMA5,
    
    /// <remarks/>
    CMA2,
    
    /// <remarks/>
    CM31,
    
    /// <remarks/>
    CM32,
    
    /// <remarks/>
    CM33,
    
    /// <remarks/>
    MCS3,
    
    /// <remarks/>
    CCA1,
    
    /// <remarks/>
    CCA2,
    
    /// <remarks/>
    CCA3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Parameter12 {
    
    private EncryptionFormat2Code ncrptnFrmtField;
    
    private bool ncrptnFrmtFieldSpecified;
    
    private byte[] initlstnVctrField;
    
    private BytePadding1Code bPddgField;
    
    private bool bPddgFieldSpecified;
    
    /// <remarks/>
    public EncryptionFormat2Code NcrptnFrmt {
        get {
            return this.ncrptnFrmtField;
        }
        set {
            this.ncrptnFrmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NcrptnFrmtSpecified {
        get {
            return this.ncrptnFrmtFieldSpecified;
        }
        set {
            this.ncrptnFrmtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] InitlstnVctr {
        get {
            return this.initlstnVctrField;
        }
        set {
            this.initlstnVctrField = value;
        }
    }
    
    /// <remarks/>
    public BytePadding1Code BPddg {
        get {
            return this.bPddgField;
        }
        set {
            this.bPddgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BPddgSpecified {
        get {
            return this.bPddgFieldSpecified;
        }
        set {
            this.bPddgFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum EncryptionFormat2Code {
    
    /// <remarks/>
    TR31,
    
    /// <remarks/>
    TR34,
    
    /// <remarks/>
    I238,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class AlgorithmIdentification29 {
    
    private Algorithm24Code algoField;
    
    private Parameter12 paramField;
    
    /// <remarks/>
    public Algorithm24Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter12 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum Algorithm24Code {
    
    /// <remarks/>
    EA2C,
    
    /// <remarks/>
    E3DC,
    
    /// <remarks/>
    DKP9,
    
    /// <remarks/>
    UKPT,
    
    /// <remarks/>
    UKA2,
    
    /// <remarks/>
    EA9C,
    
    /// <remarks/>
    EA5C,
    
    /// <remarks/>
    DA12,
    
    /// <remarks/>
    DA19,
    
    /// <remarks/>
    DA25,
    
    /// <remarks/>
    N108,
    
    /// <remarks/>
    EA5R,
    
    /// <remarks/>
    EA9R,
    
    /// <remarks/>
    EA2R,
    
    /// <remarks/>
    E3DR,
    
    /// <remarks/>
    E36C,
    
    /// <remarks/>
    E36R,
    
    /// <remarks/>
    SD5C,
    
    /// <remarks/>
    UKA1,
    
    /// <remarks/>
    UKA3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class KEK7 {
    
    private decimal vrsnField;
    
    private bool vrsnFieldSpecified;
    
    private KEKIdentifier2 kEKIdField;
    
    private AlgorithmIdentification29 keyNcrptnAlgoField;
    
    private byte[] ncrptdKeyField;
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrsnSpecified {
        get {
            return this.vrsnFieldSpecified;
        }
        set {
            this.vrsnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public KEKIdentifier2 KEKId {
        get {
            return this.kEKIdField;
        }
        set {
            this.kEKIdField = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification29 KeyNcrptnAlgo {
        get {
            return this.keyNcrptnAlgoField;
        }
        set {
            this.keyNcrptnAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] NcrptdKey {
        get {
            return this.ncrptdKeyField;
        }
        set {
            this.ncrptdKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Parameter9 {
    
    private Algorithm16Code dgstAlgoField;
    
    private bool dgstAlgoFieldSpecified;
    
    /// <remarks/>
    public Algorithm16Code DgstAlgo {
        get {
            return this.dgstAlgoField;
        }
        set {
            this.dgstAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DgstAlgoSpecified {
        get {
            return this.dgstAlgoFieldSpecified;
        }
        set {
            this.dgstAlgoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class AlgorithmIdentification18 {
    
    private Algorithm8Code algoField;
    
    private Parameter9 paramField;
    
    /// <remarks/>
    public Algorithm8Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter9 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Parameter10 {
    
    private EncryptionFormat2Code ncrptnFrmtField;
    
    private bool ncrptnFrmtFieldSpecified;
    
    private Algorithm16Code dgstAlgoField;
    
    private bool dgstAlgoFieldSpecified;
    
    private AlgorithmIdentification18 mskGnrtrAlgoField;
    
    /// <remarks/>
    public EncryptionFormat2Code NcrptnFrmt {
        get {
            return this.ncrptnFrmtField;
        }
        set {
            this.ncrptnFrmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NcrptnFrmtSpecified {
        get {
            return this.ncrptnFrmtFieldSpecified;
        }
        set {
            this.ncrptnFrmtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Algorithm16Code DgstAlgo {
        get {
            return this.dgstAlgoField;
        }
        set {
            this.dgstAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DgstAlgoSpecified {
        get {
            return this.dgstAlgoFieldSpecified;
        }
        set {
            this.dgstAlgoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification18 MskGnrtrAlgo {
        get {
            return this.mskGnrtrAlgoField;
        }
        set {
            this.mskGnrtrAlgoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class AlgorithmIdentification19 {
    
    private Algorithm7Code algoField;
    
    private Parameter10 paramField;
    
    /// <remarks/>
    public Algorithm7Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter10 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum Algorithm7Code {
    
    /// <remarks/>
    ERSA,
    
    /// <remarks/>
    RSAO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class KeyTransport5 {
    
    private decimal vrsnField;
    
    private bool vrsnFieldSpecified;
    
    private Recipient5Choice rcptIdField;
    
    private AlgorithmIdentification19 keyNcrptnAlgoField;
    
    private byte[] ncrptdKeyField;
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrsnSpecified {
        get {
            return this.vrsnFieldSpecified;
        }
        set {
            this.vrsnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Recipient5Choice RcptId {
        get {
            return this.rcptIdField;
        }
        set {
            this.rcptIdField = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification19 KeyNcrptnAlgo {
        get {
            return this.keyNcrptnAlgoField;
        }
        set {
            this.keyNcrptnAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] NcrptdKey {
        get {
            return this.ncrptdKeyField;
        }
        set {
            this.ncrptdKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Recipient8Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KEK", typeof(KEK7))]
    [System.Xml.Serialization.XmlElementAttribute("KeyIdr", typeof(KEKIdentifier2))]
    [System.Xml.Serialization.XmlElementAttribute("KeyTrnsprt", typeof(KeyTransport5))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class AuthenticatedData6 {
    
    private decimal vrsnField;
    
    private bool vrsnFieldSpecified;
    
    private Recipient8Choice[] rcptField;
    
    private AlgorithmIdentification22 mACAlgoField;
    
    private EncapsulatedContent3 ncpsltdCnttField;
    
    private byte[] mACField;
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrsnSpecified {
        get {
            return this.vrsnFieldSpecified;
        }
        set {
            this.vrsnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rcpt")]
    public Recipient8Choice[] Rcpt {
        get {
            return this.rcptField;
        }
        set {
            this.rcptField = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification22 MACAlgo {
        get {
            return this.mACAlgoField;
        }
        set {
            this.mACAlgoField = value;
        }
    }
    
    /// <remarks/>
    public EncapsulatedContent3 NcpsltdCntt {
        get {
            return this.ncpsltdCnttField;
        }
        set {
            this.ncpsltdCnttField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] MAC {
        get {
            return this.mACField;
        }
        set {
            this.mACField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class ContentInformationType21 {
    
    private ContentType2Code cnttTpField;
    
    private AuthenticatedData6 authntcdDataField;
    
    private SignedData5 sgndDataField;
    
    /// <remarks/>
    public ContentType2Code CnttTp {
        get {
            return this.cnttTpField;
        }
        set {
            this.cnttTpField = value;
        }
    }
    
    /// <remarks/>
    public AuthenticatedData6 AuthntcdData {
        get {
            return this.authntcdDataField;
        }
        set {
            this.authntcdDataField = value;
        }
    }
    
    /// <remarks/>
    public SignedData5 SgndData {
        get {
            return this.sgndDataField;
        }
        set {
            this.sgndDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class ResponseType6 {
    
    private Response2Code rspnField;
    
    private ResultDetail3Code rspnDtlField;
    
    private bool rspnDtlFieldSpecified;
    
    private string addtlRspnField;
    
    /// <remarks/>
    public Response2Code Rspn {
        get {
            return this.rspnField;
        }
        set {
            this.rspnField = value;
        }
    }
    
    /// <remarks/>
    public ResultDetail3Code RspnDtl {
        get {
            return this.rspnDtlField;
        }
        set {
            this.rspnDtlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RspnDtlSpecified {
        get {
            return this.rspnDtlFieldSpecified;
        }
        set {
            this.rspnDtlFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRspn {
        get {
            return this.addtlRspnField;
        }
        set {
            this.addtlRspnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum Response2Code {
    
    /// <remarks/>
    APPR,
    
    /// <remarks/>
    DECL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum ResultDetail3Code {
    
    /// <remarks/>
    CRTU,
    
    /// <remarks/>
    SVSU,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class CertificateManagementResponse2 {
    
    private GenericIdentification176 pOIIdField;
    
    private GenericIdentification176 tMIdField;
    
    private CardPaymentServiceType10Code certSvcField;
    
    private ResponseType6 rsltField;
    
    private string sctyPrflField;
    
    private byte[] clntCertField;
    
    private byte[][] clntCertPthField;
    
    private byte[][] svrCertPthField;
    
    /// <remarks/>
    public GenericIdentification176 POIId {
        get {
            return this.pOIIdField;
        }
        set {
            this.pOIIdField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification176 TMId {
        get {
            return this.tMIdField;
        }
        set {
            this.tMIdField = value;
        }
    }
    
    /// <remarks/>
    public CardPaymentServiceType10Code CertSvc {
        get {
            return this.certSvcField;
        }
        set {
            this.certSvcField = value;
        }
    }
    
    /// <remarks/>
    public ResponseType6 Rslt {
        get {
            return this.rsltField;
        }
        set {
            this.rsltField = value;
        }
    }
    
    /// <remarks/>
    public string SctyPrfl {
        get {
            return this.sctyPrflField;
        }
        set {
            this.sctyPrflField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] ClntCert {
        get {
            return this.clntCertField;
        }
        set {
            this.clntCertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ClntCertPth", DataType="base64Binary")]
    public byte[][] ClntCertPth {
        get {
            return this.clntCertPthField;
        }
        set {
            this.clntCertPthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SvrCertPth", DataType="base64Binary")]
    public byte[][] SvrCertPth {
        get {
            return this.svrCertPthField;
        }
        set {
            this.svrCertPthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum CardPaymentServiceType10Code {
    
    /// <remarks/>
    CRTC,
    
    /// <remarks/>
    CRTR,
    
    /// <remarks/>
    CRTK,
    
    /// <remarks/>
    WLSR,
    
    /// <remarks/>
    WLSA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Traceability8 {
    
    private GenericIdentification177 rlayIdField;
    
    private string prtcolNmField;
    
    private string prtcolVrsnField;
    
    private System.DateTime tracDtTmInField;
    
    private System.DateTime tracDtTmOutField;
    
    /// <remarks/>
    public GenericIdentification177 RlayId {
        get {
            return this.rlayIdField;
        }
        set {
            this.rlayIdField = value;
        }
    }
    
    /// <remarks/>
    public string PrtcolNm {
        get {
            return this.prtcolNmField;
        }
        set {
            this.prtcolNmField = value;
        }
    }
    
    /// <remarks/>
    public string PrtcolVrsn {
        get {
            return this.prtcolVrsnField;
        }
        set {
            this.prtcolVrsnField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TracDtTmIn {
        get {
            return this.tracDtTmInField;
        }
        set {
            this.tracDtTmInField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TracDtTmOut {
        get {
            return this.tracDtTmOutField;
        }
        set {
            this.tracDtTmOutField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class GenericIdentification177 {
    
    private string idField;
    
    private PartyType33Code tpField;
    
    private bool tpFieldSpecified;
    
    private PartyType33Code issrField;
    
    private bool issrFieldSpecified;
    
    private string ctryField;
    
    private string shrtNmField;
    
    private NetworkParameters7 rmotAccsField;
    
    private Geolocation1 glctnField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public PartyType33Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TpSpecified {
        get {
            return this.tpFieldSpecified;
        }
        set {
            this.tpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PartyType33Code Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IssrSpecified {
        get {
            return this.issrFieldSpecified;
        }
        set {
            this.issrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    public string ShrtNm {
        get {
            return this.shrtNmField;
        }
        set {
            this.shrtNmField = value;
        }
    }
    
    /// <remarks/>
    public NetworkParameters7 RmotAccs {
        get {
            return this.rmotAccsField;
        }
        set {
            this.rmotAccsField = value;
        }
    }
    
    /// <remarks/>
    public Geolocation1 Glctn {
        get {
            return this.glctnField;
        }
        set {
            this.glctnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class NetworkParameters7 {
    
    private NetworkParameters9[] adrField;
    
    private string usrNmField;
    
    private byte[] accsCdField;
    
    private byte[][] svrCertField;
    
    private byte[][] svrCertIdrField;
    
    private byte[][] clntCertField;
    
    private string sctyPrflField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Adr")]
    public NetworkParameters9[] Adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
    
    /// <remarks/>
    public string UsrNm {
        get {
            return this.usrNmField;
        }
        set {
            this.usrNmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] AccsCd {
        get {
            return this.accsCdField;
        }
        set {
            this.accsCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SvrCert", DataType="base64Binary")]
    public byte[][] SvrCert {
        get {
            return this.svrCertField;
        }
        set {
            this.svrCertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SvrCertIdr", DataType="base64Binary")]
    public byte[][] SvrCertIdr {
        get {
            return this.svrCertIdrField;
        }
        set {
            this.svrCertIdrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ClntCert", DataType="base64Binary")]
    public byte[][] ClntCert {
        get {
            return this.clntCertField;
        }
        set {
            this.clntCertField = value;
        }
    }
    
    /// <remarks/>
    public string SctyPrfl {
        get {
            return this.sctyPrflField;
        }
        set {
            this.sctyPrflField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class NetworkParameters9 {
    
    private NetworkType1Code ntwkTpField;
    
    private string adrValField;
    
    /// <remarks/>
    public NetworkType1Code NtwkTp {
        get {
            return this.ntwkTpField;
        }
        set {
            this.ntwkTpField = value;
        }
    }
    
    /// <remarks/>
    public string AdrVal {
        get {
            return this.adrValField;
        }
        set {
            this.adrValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public enum NetworkType1Code {
    
    /// <remarks/>
    IPNW,
    
    /// <remarks/>
    PSTN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class Geolocation1 {
    
    private GeolocationGeographicCoordinates1 geogcCordintsField;
    
    private GeolocationUTMCoordinates1 uTMCordintsField;
    
    /// <remarks/>
    public GeolocationGeographicCoordinates1 GeogcCordints {
        get {
            return this.geogcCordintsField;
        }
        set {
            this.geogcCordintsField = value;
        }
    }
    
    /// <remarks/>
    public GeolocationUTMCoordinates1 UTMCordints {
        get {
            return this.uTMCordintsField;
        }
        set {
            this.uTMCordintsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class GeolocationGeographicCoordinates1 {
    
    private string latField;
    
    private string longField;
    
    /// <remarks/>
    public string Lat {
        get {
            return this.latField;
        }
        set {
            this.latField = value;
        }
    }
    
    /// <remarks/>
    public string Long {
        get {
            return this.longField;
        }
        set {
            this.longField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:catm.008.001.03")]
public partial class GeolocationUTMCoordinates1 {
    
    private string uTMZoneField;
    
    private string uTMEstwrdField;
    
    private string uTMNrthwrdField;
    
    /// <remarks/>
    public string UTMZone {
        get {
            return this.uTMZoneField;
        }
        set {
            this.uTMZoneField = value;
        }
    }
    
    /// <remarks/>
    public string UTMEstwrd {
        get {
            return this.uTMEstwrdField;
        }
        set {
            this.uTMEstwrdField = value;
        }
    }
    
    /// <remarks/>
    public string UTMNrthwrd {
        get {
            return this.uTMNrthwrdField;
        }
        set {
            this.uTMNrthwrdField = value;
        }
    }
}
