//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05", IsNullable=false)]
public partial class Document {
    
    private MeetingNotificationV05 mtgNtfctnField;
    
    /// <remarks/>
    public MeetingNotificationV05 MtgNtfctn {
        get {
            return this.mtgNtfctnField;
        }
        set {
            this.mtgNtfctnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class MeetingNotificationV05 {
    
    private AmendInformation1 amdmntField;
    
    private NotificationStatus2 ntfctnStsField;
    
    private MeetingNotice4 mtgField;
    
    private Meeting4[] mtgDtlsField;
    
    private IssuerInformation2 issrField;
    
    private IssuerAgent2[] issrAgtField;
    
    private SecurityPosition8[] sctyField;
    
    private Resolution3[] rsltnField;
    
    private VoteParameters4 voteField;
    
    private EntitlementAssessment3 entitlmntSpcfctnField;
    
    private PowerOfAttorneyRequirements3 pwrOfAttnyRqrmntsField;
    
    private string[] addtlInfField;
    
    private SupplementaryData1[] splmtryDataField;
    
    /// <remarks/>
    public AmendInformation1 Amdmnt {
        get {
            return this.amdmntField;
        }
        set {
            this.amdmntField = value;
        }
    }
    
    /// <remarks/>
    public NotificationStatus2 NtfctnSts {
        get {
            return this.ntfctnStsField;
        }
        set {
            this.ntfctnStsField = value;
        }
    }
    
    /// <remarks/>
    public MeetingNotice4 Mtg {
        get {
            return this.mtgField;
        }
        set {
            this.mtgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MtgDtls")]
    public Meeting4[] MtgDtls {
        get {
            return this.mtgDtlsField;
        }
        set {
            this.mtgDtlsField = value;
        }
    }
    
    /// <remarks/>
    public IssuerInformation2 Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IssrAgt")]
    public IssuerAgent2[] IssrAgt {
        get {
            return this.issrAgtField;
        }
        set {
            this.issrAgtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Scty")]
    public SecurityPosition8[] Scty {
        get {
            return this.sctyField;
        }
        set {
            this.sctyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rsltn")]
    public Resolution3[] Rsltn {
        get {
            return this.rsltnField;
        }
        set {
            this.rsltnField = value;
        }
    }
    
    /// <remarks/>
    public VoteParameters4 Vote {
        get {
            return this.voteField;
        }
        set {
            this.voteField = value;
        }
    }
    
    /// <remarks/>
    public EntitlementAssessment3 EntitlmntSpcfctn {
        get {
            return this.entitlmntSpcfctnField;
        }
        set {
            this.entitlmntSpcfctnField = value;
        }
    }
    
    /// <remarks/>
    public PowerOfAttorneyRequirements3 PwrOfAttnyRqrmnts {
        get {
            return this.pwrOfAttnyRqrmntsField;
        }
        set {
            this.pwrOfAttnyRqrmntsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Dsclmr", IsNullable=false)]
    public string[] AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
    public SupplementaryData1[] SplmtryData {
        get {
            return this.splmtryDataField;
        }
        set {
            this.splmtryDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class AmendInformation1 {
    
    private MessageIdentification prvsRefField;
    
    private bool rcnfrmInstrsField;
    
    /// <remarks/>
    public MessageIdentification PrvsRef {
        get {
            return this.prvsRefField;
        }
        set {
            this.prvsRefField = value;
        }
    }
    
    /// <remarks/>
    public bool RcnfrmInstrs {
        get {
            return this.rcnfrmInstrsField;
        }
        set {
            this.rcnfrmInstrsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class MessageIdentification {
    
    private string idField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class SupplementaryData1 {
    
    private string plcAndNmField;
    
    private System.Xml.XmlElement envlpField;
    
    /// <remarks/>
    public string PlcAndNm {
        get {
            return this.plcAndNmField;
        }
        set {
            this.plcAndNmField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Envlp {
        get {
            return this.envlpField;
        }
        set {
            this.envlpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class PowerOfAttorneyRequirements3 {
    
    private PowerOfAttorneyLegalisation1Code[] lglRqrmntField;
    
    private string othrDcmnttnField;
    
    private DateFormat29Choice docSubmissnDdlnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LglRqrmnt")]
    public PowerOfAttorneyLegalisation1Code[] LglRqrmnt {
        get {
            return this.lglRqrmntField;
        }
        set {
            this.lglRqrmntField = value;
        }
    }
    
    /// <remarks/>
    public string OthrDcmnttn {
        get {
            return this.othrDcmnttnField;
        }
        set {
            this.othrDcmnttnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice DocSubmissnDdln {
        get {
            return this.docSubmissnDdlnField;
        }
        set {
            this.docSubmissnDdlnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum PowerOfAttorneyLegalisation1Code {
    
    /// <remarks/>
    NOTA,
    
    /// <remarks/>
    LOCA,
    
    /// <remarks/>
    APOS,
    
    /// <remarks/>
    COUN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class DateFormat29Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DtCd", typeof(DateType1Code))]
    [System.Xml.Serialization.XmlElementAttribute("DtOrDtTm", typeof(DateAndDateTimeChoice))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum DateType1Code {
    
    /// <remarks/>
    UKWN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class DateAndDateTimeChoice {
    
    private System.DateTime itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("DtTm", typeof(System.DateTime))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public System.DateTime Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    Dt,
    
    /// <remarks/>
    DtTm,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class DateFormat1 {
    
    private DateFormat3Choice dtField;
    
    private DateMode1Code dtMdField;
    
    private bool dtMdFieldSpecified;
    
    /// <remarks/>
    public DateFormat3Choice Dt {
        get {
            return this.dtField;
        }
        set {
            this.dtField = value;
        }
    }
    
    /// <remarks/>
    public DateMode1Code DtMd {
        get {
            return this.dtMdField;
        }
        set {
            this.dtMdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtMdSpecified {
        get {
            return this.dtMdFieldSpecified;
        }
        set {
            this.dtMdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class DateFormat3Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("DtCd", typeof(DateType1Code))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum DateMode1Code {
    
    /// <remarks/>
    BODY,
    
    /// <remarks/>
    EODY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class EntitlementAssessment3 {
    
    private DateFormat29Choice sctiesBlckgDdlnField;
    
    private DateFormat29Choice sctiesBlckgSTPDdlnField;
    
    private DateFormat29Choice sctiesBlckgMktDdlnField;
    
    private System.DateTime sctiesBlckgPrdEndDtField;
    
    private bool sctiesBlckgPrdEndDtFieldSpecified;
    
    private DateFormat1 entitlmntFxgDtField;
    
    private DateFormat29Choice regnSctiesDdlnField;
    
    private DateFormat29Choice regnSctiesSTPDdlnField;
    
    private DateFormat29Choice regnSctiesMktDdlnField;
    
    private DateFormat29Choice regnPrtcptnDdlnField;
    
    private DateFormat29Choice regnPrtcptnSTPDdlnField;
    
    private DateFormat29Choice regnPrtcptnMktDdlnField;
    
    private Entitlement1Choice entitlmntField;
    
    /// <remarks/>
    public DateFormat29Choice SctiesBlckgDdln {
        get {
            return this.sctiesBlckgDdlnField;
        }
        set {
            this.sctiesBlckgDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice SctiesBlckgSTPDdln {
        get {
            return this.sctiesBlckgSTPDdlnField;
        }
        set {
            this.sctiesBlckgSTPDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice SctiesBlckgMktDdln {
        get {
            return this.sctiesBlckgMktDdlnField;
        }
        set {
            this.sctiesBlckgMktDdlnField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime SctiesBlckgPrdEndDt {
        get {
            return this.sctiesBlckgPrdEndDtField;
        }
        set {
            this.sctiesBlckgPrdEndDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SctiesBlckgPrdEndDtSpecified {
        get {
            return this.sctiesBlckgPrdEndDtFieldSpecified;
        }
        set {
            this.sctiesBlckgPrdEndDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public DateFormat1 EntitlmntFxgDt {
        get {
            return this.entitlmntFxgDtField;
        }
        set {
            this.entitlmntFxgDtField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice RegnSctiesDdln {
        get {
            return this.regnSctiesDdlnField;
        }
        set {
            this.regnSctiesDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice RegnSctiesSTPDdln {
        get {
            return this.regnSctiesSTPDdlnField;
        }
        set {
            this.regnSctiesSTPDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice RegnSctiesMktDdln {
        get {
            return this.regnSctiesMktDdlnField;
        }
        set {
            this.regnSctiesMktDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice RegnPrtcptnDdln {
        get {
            return this.regnPrtcptnDdlnField;
        }
        set {
            this.regnPrtcptnDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice RegnPrtcptnSTPDdln {
        get {
            return this.regnPrtcptnSTPDdlnField;
        }
        set {
            this.regnPrtcptnSTPDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice RegnPrtcptnMktDdln {
        get {
            return this.regnPrtcptnMktDdlnField;
        }
        set {
            this.regnPrtcptnMktDdlnField = value;
        }
    }
    
    /// <remarks/>
    public Entitlement1Choice Entitlmnt {
        get {
            return this.entitlmntField;
        }
        set {
            this.entitlmntField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class Entitlement1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntitlmntDesc", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("EntitlmntRatio", typeof(decimal))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class IncentivePremiumType1Choice {
    
    private object itemField;
    
    private ItemChoiceType3 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PerAttndee", typeof(bool))]
    [System.Xml.Serialization.XmlElementAttribute("PerScty", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("PerVote", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType3 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05", IncludeInSchema=false)]
public enum ItemChoiceType3 {
    
    /// <remarks/>
    PerAttndee,
    
    /// <remarks/>
    PerScty,
    
    /// <remarks/>
    PerVote,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class ActiveOrHistoricCurrencyAnd13DecimalAmount {
    
    private string ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class PriceRateOrAmountChoice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Amt", typeof(ActiveOrHistoricCurrencyAnd13DecimalAmount))]
    [System.Xml.Serialization.XmlElementAttribute("Rate", typeof(decimal))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class IncentivePremium3 {
    
    private string descField;
    
    private PriceRateOrAmountChoice amtField;
    
    private IncentivePremiumType1Choice tpField;
    
    private DateFormat3Choice pmtDtField;
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    public PriceRateOrAmountChoice Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <remarks/>
    public IncentivePremiumType1Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat3Choice PmtDt {
        get {
            return this.pmtDtField;
        }
        set {
            this.pmtDtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class CommunicationAddress4 {
    
    private string emailAdrField;
    
    private string uRLAdrField;
    
    /// <remarks/>
    public string EmailAdr {
        get {
            return this.emailAdrField;
        }
        set {
            this.emailAdrField = value;
        }
    }
    
    /// <remarks/>
    public string URLAdr {
        get {
            return this.uRLAdrField;
        }
        set {
            this.uRLAdrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class VoteMethods2 {
    
    private string[] voteThrghNtwkField;
    
    private PostalAddress1[] voteByMailField;
    
    private CommunicationAddress4[] elctrncVoteField;
    
    private string[] voteByTelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VoteThrghNtwk")]
    public string[] VoteThrghNtwk {
        get {
            return this.voteThrghNtwkField;
        }
        set {
            this.voteThrghNtwkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VoteByMail")]
    public PostalAddress1[] VoteByMail {
        get {
            return this.voteByMailField;
        }
        set {
            this.voteByMailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElctrncVote")]
    public CommunicationAddress4[] ElctrncVote {
        get {
            return this.elctrncVoteField;
        }
        set {
            this.elctrncVoteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VoteByTel")]
    public string[] VoteByTel {
        get {
            return this.voteByTelField;
        }
        set {
            this.voteByTelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class PostalAddress1 {
    
    private AddressType2Code adrTpField;
    
    private bool adrTpFieldSpecified;
    
    private string[] adrLineField;
    
    private string strtNmField;
    
    private string bldgNbField;
    
    private string pstCdField;
    
    private string twnNmField;
    
    private string ctrySubDvsnField;
    
    private string ctryField;
    
    /// <remarks/>
    public AddressType2Code AdrTp {
        get {
            return this.adrTpField;
        }
        set {
            this.adrTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AdrTpSpecified {
        get {
            return this.adrTpFieldSpecified;
        }
        set {
            this.adrTpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
    public string[] AdrLine {
        get {
            return this.adrLineField;
        }
        set {
            this.adrLineField = value;
        }
    }
    
    /// <remarks/>
    public string StrtNm {
        get {
            return this.strtNmField;
        }
        set {
            this.strtNmField = value;
        }
    }
    
    /// <remarks/>
    public string BldgNb {
        get {
            return this.bldgNbField;
        }
        set {
            this.bldgNbField = value;
        }
    }
    
    /// <remarks/>
    public string PstCd {
        get {
            return this.pstCdField;
        }
        set {
            this.pstCdField = value;
        }
    }
    
    /// <remarks/>
    public string TwnNm {
        get {
            return this.twnNmField;
        }
        set {
            this.twnNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsn {
        get {
            return this.ctrySubDvsnField;
        }
        set {
            this.ctrySubDvsnField = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum AddressType2Code {
    
    /// <remarks/>
    ADDR,
    
    /// <remarks/>
    PBOX,
    
    /// <remarks/>
    HOME,
    
    /// <remarks/>
    BIZZ,
    
    /// <remarks/>
    MLTO,
    
    /// <remarks/>
    DLVY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class VoteParameters4 {
    
    private decimal sctiesQtyReqrdToVoteField;
    
    private bool sctiesQtyReqrdToVoteFieldSpecified;
    
    private bool prtlVoteAllwdField;
    
    private bool spltVoteAllwdField;
    
    private DateFormat29Choice voteDdlnField;
    
    private DateFormat29Choice voteSTPDdlnField;
    
    private DateFormat29Choice voteMktDdlnField;
    
    private VoteMethods2 voteMthdsField;
    
    private CommunicationAddress4 vtngBlltElctrncAdrField;
    
    private PostalAddress1 vtngBlltReqAdrField;
    
    private DateFormat29Choice rvcbltyDdlnField;
    
    private DateFormat29Choice rvcbltySTPDdlnField;
    
    private DateFormat29Choice rvcbltyMktDdlnField;
    
    private bool bnfclOwnrDsclsrField;
    
    private VoteInstruction2Code[] voteInstrTpField;
    
    private IncentivePremium3 earlyIncntivPrmField;
    
    private IncentivePremium3 incntivPrmField;
    
    private DateFormat29Choice earlyVoteWthPrmDdlnField;
    
    private DateFormat29Choice voteWthPrmDdlnField;
    
    private DateFormat29Choice voteWthPrmSTPDdlnField;
    
    private DateFormat29Choice voteWthPrmMktDdlnField;
    
    private string addtlVtngRqrmntsField;
    
    private bool prvsInstrInvldtyIndField;
    
    private bool prvsInstrInvldtyIndFieldSpecified;
    
    /// <remarks/>
    public decimal SctiesQtyReqrdToVote {
        get {
            return this.sctiesQtyReqrdToVoteField;
        }
        set {
            this.sctiesQtyReqrdToVoteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SctiesQtyReqrdToVoteSpecified {
        get {
            return this.sctiesQtyReqrdToVoteFieldSpecified;
        }
        set {
            this.sctiesQtyReqrdToVoteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool PrtlVoteAllwd {
        get {
            return this.prtlVoteAllwdField;
        }
        set {
            this.prtlVoteAllwdField = value;
        }
    }
    
    /// <remarks/>
    public bool SpltVoteAllwd {
        get {
            return this.spltVoteAllwdField;
        }
        set {
            this.spltVoteAllwdField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice VoteDdln {
        get {
            return this.voteDdlnField;
        }
        set {
            this.voteDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice VoteSTPDdln {
        get {
            return this.voteSTPDdlnField;
        }
        set {
            this.voteSTPDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice VoteMktDdln {
        get {
            return this.voteMktDdlnField;
        }
        set {
            this.voteMktDdlnField = value;
        }
    }
    
    /// <remarks/>
    public VoteMethods2 VoteMthds {
        get {
            return this.voteMthdsField;
        }
        set {
            this.voteMthdsField = value;
        }
    }
    
    /// <remarks/>
    public CommunicationAddress4 VtngBlltElctrncAdr {
        get {
            return this.vtngBlltElctrncAdrField;
        }
        set {
            this.vtngBlltElctrncAdrField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress1 VtngBlltReqAdr {
        get {
            return this.vtngBlltReqAdrField;
        }
        set {
            this.vtngBlltReqAdrField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice RvcbltyDdln {
        get {
            return this.rvcbltyDdlnField;
        }
        set {
            this.rvcbltyDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice RvcbltySTPDdln {
        get {
            return this.rvcbltySTPDdlnField;
        }
        set {
            this.rvcbltySTPDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice RvcbltyMktDdln {
        get {
            return this.rvcbltyMktDdlnField;
        }
        set {
            this.rvcbltyMktDdlnField = value;
        }
    }
    
    /// <remarks/>
    public bool BnfclOwnrDsclsr {
        get {
            return this.bnfclOwnrDsclsrField;
        }
        set {
            this.bnfclOwnrDsclsrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VoteInstrTp")]
    public VoteInstruction2Code[] VoteInstrTp {
        get {
            return this.voteInstrTpField;
        }
        set {
            this.voteInstrTpField = value;
        }
    }
    
    /// <remarks/>
    public IncentivePremium3 EarlyIncntivPrm {
        get {
            return this.earlyIncntivPrmField;
        }
        set {
            this.earlyIncntivPrmField = value;
        }
    }
    
    /// <remarks/>
    public IncentivePremium3 IncntivPrm {
        get {
            return this.incntivPrmField;
        }
        set {
            this.incntivPrmField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice EarlyVoteWthPrmDdln {
        get {
            return this.earlyVoteWthPrmDdlnField;
        }
        set {
            this.earlyVoteWthPrmDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice VoteWthPrmDdln {
        get {
            return this.voteWthPrmDdlnField;
        }
        set {
            this.voteWthPrmDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice VoteWthPrmSTPDdln {
        get {
            return this.voteWthPrmSTPDdlnField;
        }
        set {
            this.voteWthPrmSTPDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice VoteWthPrmMktDdln {
        get {
            return this.voteWthPrmMktDdlnField;
        }
        set {
            this.voteWthPrmMktDdlnField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlVtngRqrmnts {
        get {
            return this.addtlVtngRqrmntsField;
        }
        set {
            this.addtlVtngRqrmntsField = value;
        }
    }
    
    /// <remarks/>
    public bool PrvsInstrInvldtyInd {
        get {
            return this.prvsInstrInvldtyIndField;
        }
        set {
            this.prvsInstrInvldtyIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrvsInstrInvldtyIndSpecified {
        get {
            return this.prvsInstrInvldtyIndFieldSpecified;
        }
        set {
            this.prvsInstrInvldtyIndFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum VoteInstruction2Code {
    
    /// <remarks/>
    CFOR,
    
    /// <remarks/>
    CAGS,
    
    /// <remarks/>
    ABST,
    
    /// <remarks/>
    WTHH,
    
    /// <remarks/>
    WMGT,
    
    /// <remarks/>
    AMGT,
    
    /// <remarks/>
    NOAC,
    
    /// <remarks/>
    DISC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class Resolution3 {
    
    private string issrLablField;
    
    private string descField;
    
    private string titlField;
    
    private ResolutionType2Code tpField;
    
    private bool tpFieldSpecified;
    
    private bool forInfOnlyField;
    
    private ResolutionStatus1Code stsField;
    
    private bool submittdBySctyHldrField;
    
    private bool submittdBySctyHldrFieldSpecified;
    
    private VoteInstruction2Code[] voteInstrTpField;
    
    private VoteInstruction1Code mgmtRcmmndtnField;
    
    private bool mgmtRcmmndtnFieldSpecified;
    
    private VoteInstruction1Code ntifngPtyRcmmndtnField;
    
    private bool ntifngPtyRcmmndtnFieldSpecified;
    
    private Entitlement1Choice entitlmntField;
    
    /// <remarks/>
    public string IssrLabl {
        get {
            return this.issrLablField;
        }
        set {
            this.issrLablField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    public string Titl {
        get {
            return this.titlField;
        }
        set {
            this.titlField = value;
        }
    }
    
    /// <remarks/>
    public ResolutionType2Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TpSpecified {
        get {
            return this.tpFieldSpecified;
        }
        set {
            this.tpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool ForInfOnly {
        get {
            return this.forInfOnlyField;
        }
        set {
            this.forInfOnlyField = value;
        }
    }
    
    /// <remarks/>
    public ResolutionStatus1Code Sts {
        get {
            return this.stsField;
        }
        set {
            this.stsField = value;
        }
    }
    
    /// <remarks/>
    public bool SubmittdBySctyHldr {
        get {
            return this.submittdBySctyHldrField;
        }
        set {
            this.submittdBySctyHldrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubmittdBySctyHldrSpecified {
        get {
            return this.submittdBySctyHldrFieldSpecified;
        }
        set {
            this.submittdBySctyHldrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VoteInstrTp")]
    public VoteInstruction2Code[] VoteInstrTp {
        get {
            return this.voteInstrTpField;
        }
        set {
            this.voteInstrTpField = value;
        }
    }
    
    /// <remarks/>
    public VoteInstruction1Code MgmtRcmmndtn {
        get {
            return this.mgmtRcmmndtnField;
        }
        set {
            this.mgmtRcmmndtnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MgmtRcmmndtnSpecified {
        get {
            return this.mgmtRcmmndtnFieldSpecified;
        }
        set {
            this.mgmtRcmmndtnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public VoteInstruction1Code NtifngPtyRcmmndtn {
        get {
            return this.ntifngPtyRcmmndtnField;
        }
        set {
            this.ntifngPtyRcmmndtnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NtifngPtyRcmmndtnSpecified {
        get {
            return this.ntifngPtyRcmmndtnFieldSpecified;
        }
        set {
            this.ntifngPtyRcmmndtnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Entitlement1Choice Entitlmnt {
        get {
            return this.entitlmntField;
        }
        set {
            this.entitlmntField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum ResolutionType2Code {
    
    /// <remarks/>
    EXTR,
    
    /// <remarks/>
    SPCL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum ResolutionStatus1Code {
    
    /// <remarks/>
    ACTV,
    
    /// <remarks/>
    WDRA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum VoteInstruction1Code {
    
    /// <remarks/>
    CFOR,
    
    /// <remarks/>
    CAGS,
    
    /// <remarks/>
    ABST,
    
    /// <remarks/>
    WTHH,
    
    /// <remarks/>
    NOAC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class GenericIdentification20 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class GenericIdentification21 {
    
    private GenericIdentification20 tpField;
    
    private string idField;
    
    /// <remarks/>
    public GenericIdentification20 Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class SafekeepingPlaceTypeAndAnyBICIdentifier1 {
    
    private SafekeepingPlace1Code sfkpgPlcTpField;
    
    private string idField;
    
    /// <remarks/>
    public SafekeepingPlace1Code SfkpgPlcTp {
        get {
            return this.sfkpgPlcTpField;
        }
        set {
            this.sfkpgPlcTpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum SafekeepingPlace1Code {
    
    /// <remarks/>
    CUST,
    
    /// <remarks/>
    ICSD,
    
    /// <remarks/>
    NCSD,
    
    /// <remarks/>
    SHHE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class SafekeepingPlaceTypeAndText2 {
    
    private SafekeepingPlace2Code sfkpgPlcTpField;
    
    private string idField;
    
    /// <remarks/>
    public SafekeepingPlace2Code SfkpgPlcTp {
        get {
            return this.sfkpgPlcTpField;
        }
        set {
            this.sfkpgPlcTpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum SafekeepingPlace2Code {
    
    /// <remarks/>
    SHHE,
    
    /// <remarks/>
    ALLP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class SafekeepingPlaceFormat2Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ctry", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Id", typeof(SafekeepingPlaceTypeAndText2))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification21))]
    [System.Xml.Serialization.XmlElementAttribute("TpAndId", typeof(SafekeepingPlaceTypeAndAnyBICIdentifier1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class HoldingBalance7 {
    
    private UnitOrFaceAmount1Choice balField;
    
    private SecuritiesEntryType2Code balTpField;
    
    private bool balTpFieldSpecified;
    
    private SafekeepingPlaceFormat2Choice sfkpgPlcField;
    
    private System.DateTime dtField;
    
    private bool dtFieldSpecified;
    
    /// <remarks/>
    public UnitOrFaceAmount1Choice Bal {
        get {
            return this.balField;
        }
        set {
            this.balField = value;
        }
    }
    
    /// <remarks/>
    public SecuritiesEntryType2Code BalTp {
        get {
            return this.balTpField;
        }
        set {
            this.balTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BalTpSpecified {
        get {
            return this.balTpFieldSpecified;
        }
        set {
            this.balTpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public SafekeepingPlaceFormat2Choice SfkpgPlc {
        get {
            return this.sfkpgPlcField;
        }
        set {
            this.sfkpgPlcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Dt {
        get {
            return this.dtField;
        }
        set {
            this.dtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtSpecified {
        get {
            return this.dtFieldSpecified;
        }
        set {
            this.dtFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class UnitOrFaceAmount1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FaceAmt", typeof(ActiveCurrencyAndAmount))]
    [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(decimal))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class ActiveCurrencyAndAmount {
    
    private string ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum SecuritiesEntryType2Code {
    
    /// <remarks/>
    BLOK,
    
    /// <remarks/>
    ELIG,
    
    /// <remarks/>
    PEND,
    
    /// <remarks/>
    PENR,
    
    /// <remarks/>
    NOMI,
    
    /// <remarks/>
    SETD,
    
    /// <remarks/>
    BORR,
    
    /// <remarks/>
    LOAN,
    
    /// <remarks/>
    SPOS,
    
    /// <remarks/>
    TRAD,
    
    /// <remarks/>
    COLI,
    
    /// <remarks/>
    COLO,
    
    /// <remarks/>
    UNBA,
    
    /// <remarks/>
    INBA,
    
    /// <remarks/>
    REGO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class EligiblePosition5 {
    
    private string acctIdField;
    
    private PartyIdentification40Choice acctOwnrField;
    
    private HoldingBalance7[] hldgBalField;
    
    private PartyIdentification40Choice[] rghtsHldrField;
    
    /// <remarks/>
    public string AcctId {
        get {
            return this.acctIdField;
        }
        set {
            this.acctIdField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification40Choice AcctOwnr {
        get {
            return this.acctOwnrField;
        }
        set {
            this.acctOwnrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HldgBal")]
    public HoldingBalance7[] HldgBal {
        get {
            return this.hldgBalField;
        }
        set {
            this.hldgBalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RghtsHldr")]
    public PartyIdentification40Choice[] RghtsHldr {
        get {
            return this.rghtsHldrField;
        }
        set {
            this.rghtsHldrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class PartyIdentification40Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NmAndAdr", typeof(NameAndAddress5))]
    [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification19))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class NameAndAddress5 {
    
    private string nmField;
    
    private PostalAddress1 adrField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress1 Adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class GenericIdentification19 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class IdentificationSource3Choice {
    
    private string itemField;
    
    private ItemChoiceType2 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType2 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05", IncludeInSchema=false)]
public enum ItemChoiceType2 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class OtherIdentification1 {
    
    private string idField;
    
    private string sfxField;
    
    private IdentificationSource3Choice tpField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Sfx {
        get {
            return this.sfxField;
        }
        set {
            this.sfxField = value;
        }
    }
    
    /// <remarks/>
    public IdentificationSource3Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class SecurityIdentification14 {
    
    private string iSINField;
    
    private OtherIdentification1[] othrIdField;
    
    private string descField;
    
    /// <remarks/>
    public string ISIN {
        get {
            return this.iSINField;
        }
        set {
            this.iSINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OthrId")]
    public OtherIdentification1[] OthrId {
        get {
            return this.othrIdField;
        }
        set {
            this.othrIdField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class SecurityPosition8 {
    
    private SecurityIdentification14 finInstrmIdField;
    
    private EligiblePosition5[] posField;
    
    /// <remarks/>
    public SecurityIdentification14 FinInstrmId {
        get {
            return this.finInstrmIdField;
        }
        set {
            this.finInstrmIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pos")]
    public EligiblePosition5[] Pos {
        get {
            return this.posField;
        }
        set {
            this.posField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class IssuerAgent2 {
    
    private PartyIdentification40Choice idField;
    
    private AgentRole1Code roleField;
    
    private bool roleFieldSpecified;
    
    /// <remarks/>
    public PartyIdentification40Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public AgentRole1Code Role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RoleSpecified {
        get {
            return this.roleFieldSpecified;
        }
        set {
            this.roleFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum AgentRole1Code {
    
    /// <remarks/>
    PRIN,
    
    /// <remarks/>
    SUBA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class IssuerInformation2 {
    
    private PartyIdentification40Choice idField;
    
    private string uRLAdrField;
    
    /// <remarks/>
    public PartyIdentification40Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string URLAdr {
        get {
            return this.uRLAdrField;
        }
        set {
            this.uRLAdrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class QuorumQuantity1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("QrmQty", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QrmQtyPctg", typeof(decimal))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class LocationFormat1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Adr", typeof(PostalAddress1))]
    [System.Xml.Serialization.XmlElementAttribute("LctnCd", typeof(PlaceType1Code))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum PlaceType1Code {
    
    /// <remarks/>
    UKWN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class Meeting4 {
    
    private DateFormat29Choice dtAndTmField;
    
    private MeetingDateStatus1Code dtStsField;
    
    private bool dtStsFieldSpecified;
    
    private bool qrmReqrdField;
    
    private LocationFormat1Choice[] lctnField;
    
    private QuorumQuantity1Choice qrmQtyField;
    
    /// <remarks/>
    public DateFormat29Choice DtAndTm {
        get {
            return this.dtAndTmField;
        }
        set {
            this.dtAndTmField = value;
        }
    }
    
    /// <remarks/>
    public MeetingDateStatus1Code DtSts {
        get {
            return this.dtStsField;
        }
        set {
            this.dtStsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtStsSpecified {
        get {
            return this.dtStsFieldSpecified;
        }
        set {
            this.dtStsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool QrmReqrd {
        get {
            return this.qrmReqrdField;
        }
        set {
            this.qrmReqrdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Lctn")]
    public LocationFormat1Choice[] Lctn {
        get {
            return this.lctnField;
        }
        set {
            this.lctnField = value;
        }
    }
    
    /// <remarks/>
    public QuorumQuantity1Choice QrmQty {
        get {
            return this.qrmQtyField;
        }
        set {
            this.qrmQtyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum MeetingDateStatus1Code {
    
    /// <remarks/>
    TNTA,
    
    /// <remarks/>
    CNFR,
    
    /// <remarks/>
    CANC,
    
    /// <remarks/>
    NOQO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class ContactIdentification1 {
    
    private string nmField;
    
    private NamePrefix1Code nmPrfxField;
    
    private bool nmPrfxFieldSpecified;
    
    private string gvnNmField;
    
    private string roleField;
    
    private string phneNbField;
    
    private string faxNbField;
    
    private string emailAdrField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public NamePrefix1Code NmPrfx {
        get {
            return this.nmPrfxField;
        }
        set {
            this.nmPrfxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NmPrfxSpecified {
        get {
            return this.nmPrfxFieldSpecified;
        }
        set {
            this.nmPrfxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string GvnNm {
        get {
            return this.gvnNmField;
        }
        set {
            this.gvnNmField = value;
        }
    }
    
    /// <remarks/>
    public string Role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
    
    /// <remarks/>
    public string PhneNb {
        get {
            return this.phneNbField;
        }
        set {
            this.phneNbField = value;
        }
    }
    
    /// <remarks/>
    public string FaxNb {
        get {
            return this.faxNbField;
        }
        set {
            this.faxNbField = value;
        }
    }
    
    /// <remarks/>
    public string EmailAdr {
        get {
            return this.emailAdrField;
        }
        set {
            this.emailAdrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum NamePrefix1Code {
    
    /// <remarks/>
    DOCT,
    
    /// <remarks/>
    MIST,
    
    /// <remarks/>
    MISS,
    
    /// <remarks/>
    MADM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class MeetingContactPerson2 {
    
    private ContactIdentification1 ctctPrsnField;
    
    private PartyIdentification40Choice emplngPtyField;
    
    private string plcOfListgField;
    
    /// <remarks/>
    public ContactIdentification1 CtctPrsn {
        get {
            return this.ctctPrsnField;
        }
        set {
            this.ctctPrsnField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification40Choice EmplngPty {
        get {
            return this.emplngPtyField;
        }
        set {
            this.emplngPtyField = value;
        }
    }
    
    /// <remarks/>
    public string PlcOfListg {
        get {
            return this.plcOfListgField;
        }
        set {
            this.plcOfListgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class LongPostalAddress2Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Strd", typeof(PostalAddress1))]
    [System.Xml.Serialization.XmlElementAttribute("Ustrd", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class GenericIdentification4 {
    
    private string idField;
    
    private string idTpField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string IdTp {
        get {
            return this.idTpField;
        }
        set {
            this.idTpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class PersonIdentificationType1Choice {
    
    private object itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AlnRegnNb", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("DrvrsLicNb", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IdntyCardNb", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MplyrIdNb", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("OthrId", typeof(GenericIdentification4))]
    [System.Xml.Serialization.XmlElementAttribute("PsptNb", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("SclSctyNb", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("TaxIdNb", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    AlnRegnNb,
    
    /// <remarks/>
    DrvrsLicNb,
    
    /// <remarks/>
    IdntyCardNb,
    
    /// <remarks/>
    MplyrIdNb,
    
    /// <remarks/>
    OthrId,
    
    /// <remarks/>
    PsptNb,
    
    /// <remarks/>
    SclSctyNb,
    
    /// <remarks/>
    TaxIdNb,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class PersonIdentification6 {
    
    private string issrField;
    
    private PersonIdentificationType1Choice prsnIdTpField;
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public PersonIdentificationType1Choice PrsnIdTp {
        get {
            return this.prsnIdTpField;
        }
        set {
            this.prsnIdTpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class IndividualPerson25 {
    
    private string birthNmField;
    
    private string gvnNmField;
    
    private PersonIdentification6 idField;
    
    private LongPostalAddress2Choice adrField;
    
    private PartyIdentification40Choice emplngPtyField;
    
    /// <remarks/>
    public string BirthNm {
        get {
            return this.birthNmField;
        }
        set {
            this.birthNmField = value;
        }
    }
    
    /// <remarks/>
    public string GvnNm {
        get {
            return this.gvnNmField;
        }
        set {
            this.gvnNmField = value;
        }
    }
    
    /// <remarks/>
    public PersonIdentification6 Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public LongPostalAddress2Choice Adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification40Choice EmplngPty {
        get {
            return this.emplngPtyField;
        }
        set {
            this.emplngPtyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class Proxy5 {
    
    private ProxyType2Code[] prxyTpField;
    
    private IndividualPerson25 prssgndPrxyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PrxyTp")]
    public ProxyType2Code[] PrxyTp {
        get {
            return this.prxyTpField;
        }
        set {
            this.prxyTpField = value;
        }
    }
    
    /// <remarks/>
    public IndividualPerson25 PrssgndPrxy {
        get {
            return this.prssgndPrxyField;
        }
        set {
            this.prssgndPrxyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum ProxyType2Code {
    
    /// <remarks/>
    CHRM,
    
    /// <remarks/>
    DISC,
    
    /// <remarks/>
    HLDR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class ProxyAppointmentInformation3 {
    
    private string regnMtdField;
    
    private DateFormat29Choice ddlnField;
    
    private DateFormat29Choice sTPDdlnField;
    
    private DateFormat29Choice mktDdlnField;
    
    private Proxy5[] authrsdPrxyField;
    
    /// <remarks/>
    public string RegnMtd {
        get {
            return this.regnMtdField;
        }
        set {
            this.regnMtdField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice Ddln {
        get {
            return this.ddlnField;
        }
        set {
            this.ddlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice STPDdln {
        get {
            return this.sTPDdlnField;
        }
        set {
            this.sTPDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice MktDdln {
        get {
            return this.mktDdlnField;
        }
        set {
            this.mktDdlnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AuthrsdPrxy")]
    public Proxy5[] AuthrsdPrxy {
        get {
            return this.authrsdPrxyField;
        }
        set {
            this.authrsdPrxyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class Proxy2Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Prxy", typeof(ProxyAppointmentInformation3))]
    [System.Xml.Serialization.XmlElementAttribute("PrxyNotAllwd", typeof(ProxyNotAllowedCode))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum ProxyNotAllowedCode {
    
    /// <remarks/>
    NPRO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class AdditionalRightThreshold1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlRghtThrshld", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("AddtlRghtThrshldPctg", typeof(decimal))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class AdditionalRightCode1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(AdditionalRight1Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification13))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum AdditionalRight1Code {
    
    /// <remarks/>
    WQPS,
    
    /// <remarks/>
    RSPS,
    
    /// <remarks/>
    AIPS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class GenericIdentification13 {
    
    private string idField;
    
    private string schmeNmField;
    
    private string issrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class AdditionalRights2 {
    
    private AdditionalRightCode1Choice addtlRghtField;
    
    private string addtlRghtInfURLAdrField;
    
    private DateFormat29Choice addtlRghtDdlnField;
    
    private DateFormat29Choice addtlRghtMktDdlnField;
    
    private AdditionalRightThreshold1Choice addtlRghtThrshldField;
    
    /// <remarks/>
    public AdditionalRightCode1Choice AddtlRght {
        get {
            return this.addtlRghtField;
        }
        set {
            this.addtlRghtField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRghtInfURLAdr {
        get {
            return this.addtlRghtInfURLAdrField;
        }
        set {
            this.addtlRghtInfURLAdrField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice AddtlRghtDdln {
        get {
            return this.addtlRghtDdlnField;
        }
        set {
            this.addtlRghtDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice AddtlRghtMktDdln {
        get {
            return this.addtlRghtMktDdlnField;
        }
        set {
            this.addtlRghtMktDdlnField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalRightThreshold1Choice AddtlRghtThrshld {
        get {
            return this.addtlRghtThrshldField;
        }
        set {
            this.addtlRghtThrshldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class MeetingTypeClassification1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(MeetingTypeClassification1Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification13))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum MeetingTypeClassification1Code {
    
    /// <remarks/>
    AMET,
    
    /// <remarks/>
    OMET,
    
    /// <remarks/>
    CLAS,
    
    /// <remarks/>
    ISSU,
    
    /// <remarks/>
    VRHI,
    
    /// <remarks/>
    CORT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class MeetingNotice4 {
    
    private string mtgIdField;
    
    private string issrMtgIdField;
    
    private MeetingType3Code tpField;
    
    private MeetingTypeClassification1Choice clssfctnField;
    
    private System.DateTime anncmntDtField;
    
    private bool anncmntDtFieldSpecified;
    
    private bool attndncReqrdField;
    
    private bool attndncReqrdFieldSpecified;
    
    private string attndncConfInfField;
    
    private DateFormat29Choice attndncConfDdlnField;
    
    private DateFormat29Choice attndncConfSTPDdlnField;
    
    private DateFormat29Choice attndncConfMktDdlnField;
    
    private string addtlDcmnttnURLAdrField;
    
    private AdditionalRights2[] addtlPrcdrDtlsField;
    
    private UnitOrFaceAmount1Choice ttlNbOfSctiesOutsdngField;
    
    private decimal ttlNbOfVtngRghtsField;
    
    private bool ttlNbOfVtngRghtsFieldSpecified;
    
    private PostalAddress1 prxyAppntmntNtfctnAdrField;
    
    private Proxy2Choice prxyChcField;
    
    private MeetingContactPerson2[] ctctPrsnDtlsField;
    
    private DateFormat3Choice rsltPblctnDtField;
    
    /// <remarks/>
    public string MtgId {
        get {
            return this.mtgIdField;
        }
        set {
            this.mtgIdField = value;
        }
    }
    
    /// <remarks/>
    public string IssrMtgId {
        get {
            return this.issrMtgIdField;
        }
        set {
            this.issrMtgIdField = value;
        }
    }
    
    /// <remarks/>
    public MeetingType3Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public MeetingTypeClassification1Choice Clssfctn {
        get {
            return this.clssfctnField;
        }
        set {
            this.clssfctnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime AnncmntDt {
        get {
            return this.anncmntDtField;
        }
        set {
            this.anncmntDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AnncmntDtSpecified {
        get {
            return this.anncmntDtFieldSpecified;
        }
        set {
            this.anncmntDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool AttndncReqrd {
        get {
            return this.attndncReqrdField;
        }
        set {
            this.attndncReqrdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AttndncReqrdSpecified {
        get {
            return this.attndncReqrdFieldSpecified;
        }
        set {
            this.attndncReqrdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string AttndncConfInf {
        get {
            return this.attndncConfInfField;
        }
        set {
            this.attndncConfInfField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice AttndncConfDdln {
        get {
            return this.attndncConfDdlnField;
        }
        set {
            this.attndncConfDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice AttndncConfSTPDdln {
        get {
            return this.attndncConfSTPDdlnField;
        }
        set {
            this.attndncConfSTPDdlnField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat29Choice AttndncConfMktDdln {
        get {
            return this.attndncConfMktDdlnField;
        }
        set {
            this.attndncConfMktDdlnField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlDcmnttnURLAdr {
        get {
            return this.addtlDcmnttnURLAdrField;
        }
        set {
            this.addtlDcmnttnURLAdrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlPrcdrDtls")]
    public AdditionalRights2[] AddtlPrcdrDtls {
        get {
            return this.addtlPrcdrDtlsField;
        }
        set {
            this.addtlPrcdrDtlsField = value;
        }
    }
    
    /// <remarks/>
    public UnitOrFaceAmount1Choice TtlNbOfSctiesOutsdng {
        get {
            return this.ttlNbOfSctiesOutsdngField;
        }
        set {
            this.ttlNbOfSctiesOutsdngField = value;
        }
    }
    
    /// <remarks/>
    public decimal TtlNbOfVtngRghts {
        get {
            return this.ttlNbOfVtngRghtsField;
        }
        set {
            this.ttlNbOfVtngRghtsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TtlNbOfVtngRghtsSpecified {
        get {
            return this.ttlNbOfVtngRghtsFieldSpecified;
        }
        set {
            this.ttlNbOfVtngRghtsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress1 PrxyAppntmntNtfctnAdr {
        get {
            return this.prxyAppntmntNtfctnAdrField;
        }
        set {
            this.prxyAppntmntNtfctnAdrField = value;
        }
    }
    
    /// <remarks/>
    public Proxy2Choice PrxyChc {
        get {
            return this.prxyChcField;
        }
        set {
            this.prxyChcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CtctPrsnDtls")]
    public MeetingContactPerson2[] CtctPrsnDtls {
        get {
            return this.ctctPrsnDtlsField;
        }
        set {
            this.ctctPrsnDtlsField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat3Choice RsltPblctnDt {
        get {
            return this.rsltPblctnDtField;
        }
        set {
            this.rsltPblctnDtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum MeetingType3Code {
    
    /// <remarks/>
    XMET,
    
    /// <remarks/>
    GMET,
    
    /// <remarks/>
    MIXD,
    
    /// <remarks/>
    SPCL,
    
    /// <remarks/>
    BMET,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public partial class NotificationStatus2 {
    
    private NotificationStatus2Code stsField;
    
    /// <remarks/>
    public NotificationStatus2Code Sts {
        get {
            return this.stsField;
        }
        set {
            this.stsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.001.001.05")]
public enum NotificationStatus2Code {
    
    /// <remarks/>
    ECON,
    
    /// <remarks/>
    EUNC,
}
