//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06", IsNullable=false)]
public partial class Document {
    
    private SecuritiesSettlementConditionModificationStatusAdviceV06 sctiesSttlmCondModStsAdvcField;
    
    /// <remarks/>
    public SecuritiesSettlementConditionModificationStatusAdviceV06 SctiesSttlmCondModStsAdvc {
        get {
            return this.sctiesSttlmCondModStsAdvcField;
        }
        set {
            this.sctiesSttlmCondModStsAdvcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class SecuritiesSettlementConditionModificationStatusAdviceV06 {
    
    private Identification1 reqRefField;
    
    private PartyIdentification36Choice acctOwnrField;
    
    private SecuritiesAccount13 sfkpgAcctField;
    
    private RequestDetails13 reqDtlsField;
    
    private ProcessingStatus44Choice prcgStsField;
    
    private SupplementaryData1[] splmtryDataField;
    
    /// <remarks/>
    public Identification1 ReqRef {
        get {
            return this.reqRefField;
        }
        set {
            this.reqRefField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification36Choice AcctOwnr {
        get {
            return this.acctOwnrField;
        }
        set {
            this.acctOwnrField = value;
        }
    }
    
    /// <remarks/>
    public SecuritiesAccount13 SfkpgAcct {
        get {
            return this.sfkpgAcctField;
        }
        set {
            this.sfkpgAcctField = value;
        }
    }
    
    /// <remarks/>
    public RequestDetails13 ReqDtls {
        get {
            return this.reqDtlsField;
        }
        set {
            this.reqDtlsField = value;
        }
    }
    
    /// <remarks/>
    public ProcessingStatus44Choice PrcgSts {
        get {
            return this.prcgStsField;
        }
        set {
            this.prcgStsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
    public SupplementaryData1[] SplmtryData {
        get {
            return this.splmtryDataField;
        }
        set {
            this.splmtryDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class Identification1 {
    
    private string idField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class SupplementaryData1 {
    
    private string plcAndNmField;
    
    private System.Xml.XmlElement envlpField;
    
    /// <remarks/>
    public string PlcAndNm {
        get {
            return this.plcAndNmField;
        }
        set {
            this.plcAndNmField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Envlp {
        get {
            return this.envlpField;
        }
        set {
            this.envlpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class ProprietaryStatusAndReason1 {
    
    private GenericIdentification20 prtryStsField;
    
    private ProprietaryReason1[] prtryRsnField;
    
    /// <remarks/>
    public GenericIdentification20 PrtrySts {
        get {
            return this.prtryStsField;
        }
        set {
            this.prtryStsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PrtryRsn")]
    public ProprietaryReason1[] PrtryRsn {
        get {
            return this.prtryRsnField;
        }
        set {
            this.prtryRsnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class GenericIdentification20 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class ProprietaryReason1 {
    
    private GenericIdentification20 rsnField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public GenericIdentification20 Rsn {
        get {
            return this.rsnField;
        }
        set {
            this.rsnField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class PendingReason2Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(PendingReason6Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum PendingReason6Code {
    
    /// <remarks/>
    ADEA,
    
    /// <remarks/>
    CONF,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    CDRG,
    
    /// <remarks/>
    CDCY,
    
    /// <remarks/>
    CDRE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class PendingReason2 {
    
    private PendingReason2Choice cdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public PendingReason2Choice Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class PendingStatus13Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(PendingReason2))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum NoReasonCode {
    
    /// <remarks/>
    NORE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class GenericIdentification40 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class DeniedReason7Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(DeniedReason6Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification40))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum DeniedReason6Code {
    
    /// <remarks/>
    ADEA,
    
    /// <remarks/>
    CDCY,
    
    /// <remarks/>
    CDRE,
    
    /// <remarks/>
    DCAN,
    
    /// <remarks/>
    DSET,
    
    /// <remarks/>
    DPRG,
    
    /// <remarks/>
    DREP,
    
    /// <remarks/>
    LATE,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    CDRG,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class DeniedReason5 {
    
    private DeniedReason7Choice cdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public DeniedReason7Choice Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class DeniedStatus10Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(DeniedReason5))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class RejectionAndRepairReason13Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(RejectionReason27Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum RejectionReason27Code {
    
    /// <remarks/>
    ADEA,
    
    /// <remarks/>
    LATE,
    
    /// <remarks/>
    SAFE,
    
    /// <remarks/>
    NRGM,
    
    /// <remarks/>
    NRGN,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    REFE,
    
    /// <remarks/>
    INVM,
    
    /// <remarks/>
    INVL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class RejectionOrRepairReason13 {
    
    private RejectionAndRepairReason13Choice cdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public RejectionAndRepairReason13Choice Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class RejectionOrRepairStatus14Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(RejectionOrRepairReason13))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class AcknowledgementReason4Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(AcknowledgementReason5Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum AcknowledgementReason5Code {
    
    /// <remarks/>
    ADEA,
    
    /// <remarks/>
    SMPG,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    CDCY,
    
    /// <remarks/>
    CDRG,
    
    /// <remarks/>
    CDRE,
    
    /// <remarks/>
    NSTP,
    
    /// <remarks/>
    RQWV,
    
    /// <remarks/>
    LATE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class AcknowledgementReason3 {
    
    private AcknowledgementReason4Choice cdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public AcknowledgementReason4Choice Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class AcknowledgedAcceptedStatus7Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(AcknowledgementReason3))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class ProcessingStatus44Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AckdAccptd", typeof(AcknowledgedAcceptedStatus7Choice))]
    [System.Xml.Serialization.XmlElementAttribute("Cmpltd", typeof(ProprietaryReason1))]
    [System.Xml.Serialization.XmlElementAttribute("Dnd", typeof(DeniedStatus10Choice))]
    [System.Xml.Serialization.XmlElementAttribute("Pdg", typeof(PendingStatus13Choice))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(ProprietaryStatusAndReason1))]
    [System.Xml.Serialization.XmlElementAttribute("Rjctd", typeof(RejectionOrRepairStatus14Choice))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class References24Choice {
    
    private string itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AcctSvcrTxId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CmonId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IntraBalMvmntId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IntraPosMvmntId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MktInfrstrctrTxId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("OthrTxId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PoolId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("SctiesSttlmTxId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("TradId", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    AcctSvcrTxId,
    
    /// <remarks/>
    CmonId,
    
    /// <remarks/>
    IntraBalMvmntId,
    
    /// <remarks/>
    IntraPosMvmntId,
    
    /// <remarks/>
    MktInfrstrctrTxId,
    
    /// <remarks/>
    OthrTxId,
    
    /// <remarks/>
    PoolId,
    
    /// <remarks/>
    SctiesSttlmTxId,
    
    /// <remarks/>
    TradId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class DocumentNumber1Choice {
    
    private object itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LngNb", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PrtryNb", typeof(GenericIdentification19))]
    [System.Xml.Serialization.XmlElementAttribute("ShrtNb", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class GenericIdentification19 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    LngNb,
    
    /// <remarks/>
    PrtryNb,
    
    /// <remarks/>
    ShrtNb,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class ProcessingPosition5Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(ProcessingPosition4Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum ProcessingPosition4Code {
    
    /// <remarks/>
    AFTE,
    
    /// <remarks/>
    BEFO,
    
    /// <remarks/>
    WITH,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class Linkages27 {
    
    private ProcessingPosition5Choice prcgPosField;
    
    private DocumentNumber1Choice msgNbField;
    
    private References24Choice refField;
    
    private PartyIdentification36Choice refOwnrField;
    
    /// <remarks/>
    public ProcessingPosition5Choice PrcgPos {
        get {
            return this.prcgPosField;
        }
        set {
            this.prcgPosField = value;
        }
    }
    
    /// <remarks/>
    public DocumentNumber1Choice MsgNb {
        get {
            return this.msgNbField;
        }
        set {
            this.msgNbField = value;
        }
    }
    
    /// <remarks/>
    public References24Choice Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification36Choice RefOwnr {
        get {
            return this.refOwnrField;
        }
        set {
            this.refOwnrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class PartyIdentification36Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification19))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class UnilateralSplit1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(SecuritiesTransactionType5Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum SecuritiesTransactionType5Code {
    
    /// <remarks/>
    TRAD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class MatchingDenied1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(MatchingProcess1Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum MatchingProcess1Code {
    
    /// <remarks/>
    UNMT,
    
    /// <remarks/>
    MTRE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class Registration7Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(Registration2Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum Registration2Code {
    
    /// <remarks/>
    PTYH,
    
    /// <remarks/>
    CSDH,
    
    /// <remarks/>
    CDEL,
    
    /// <remarks/>
    CVAL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class RegistrationReason3 {
    
    private Registration7Choice cdField;
    
    private string addtlInfField;
    
    /// <remarks/>
    public Registration7Choice Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class HoldIndicator4 {
    
    private bool indField;
    
    private RegistrationReason3[] rsnField;
    
    /// <remarks/>
    public bool Ind {
        get {
            return this.indField;
        }
        set {
            this.indField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rsn")]
    public RegistrationReason3[] Rsn {
        get {
            return this.rsnField;
        }
        set {
            this.rsnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class SecuritiesRTGS1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ind", typeof(bool))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class PriorityNumeric1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Nmrc", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class LinkageType1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(LinkageType1Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum LinkageType1Code {
    
    /// <remarks/>
    LINK,
    
    /// <remarks/>
    UNLK,
    
    /// <remarks/>
    SOFT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class AutomaticBorrowing2Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(AutoBorrowing2Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification20))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum AutoBorrowing2Code {
    
    /// <remarks/>
    LAMI,
    
    /// <remarks/>
    NBOR,
    
    /// <remarks/>
    YBOR,
    
    /// <remarks/>
    RTRN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class References16 {
    
    private string acctOwnrTxIdField;
    
    private string acctSvcrTxIdField;
    
    private string mktInfrstrctrTxIdField;
    
    private string prcrTxIdField;
    
    private string poolIdField;
    
    private string cmonIdField;
    
    private string tradIdField;
    
    /// <remarks/>
    public string AcctOwnrTxId {
        get {
            return this.acctOwnrTxIdField;
        }
        set {
            this.acctOwnrTxIdField = value;
        }
    }
    
    /// <remarks/>
    public string AcctSvcrTxId {
        get {
            return this.acctSvcrTxIdField;
        }
        set {
            this.acctSvcrTxIdField = value;
        }
    }
    
    /// <remarks/>
    public string MktInfrstrctrTxId {
        get {
            return this.mktInfrstrctrTxIdField;
        }
        set {
            this.mktInfrstrctrTxIdField = value;
        }
    }
    
    /// <remarks/>
    public string PrcrTxId {
        get {
            return this.prcrTxIdField;
        }
        set {
            this.prcrTxIdField = value;
        }
    }
    
    /// <remarks/>
    public string PoolId {
        get {
            return this.poolIdField;
        }
        set {
            this.poolIdField = value;
        }
    }
    
    /// <remarks/>
    public string CmonId {
        get {
            return this.cmonIdField;
        }
        set {
            this.cmonIdField = value;
        }
    }
    
    /// <remarks/>
    public string TradId {
        get {
            return this.tradIdField;
        }
        set {
            this.tradIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class RequestDetails13 {
    
    private References16 refField;
    
    private AutomaticBorrowing2Choice automtcBrrwgField;
    
    private bool rtnIndField;
    
    private bool rtnIndFieldSpecified;
    
    private LinkageType1Choice lkgField;
    
    private PriorityNumeric1Choice prtyField;
    
    private GenericIdentification20[] othrPrcgField;
    
    private SettlementTransactionCondition5Code prtlSttlmIndField;
    
    private bool prtlSttlmIndFieldSpecified;
    
    private SecuritiesRTGS1Choice sctiesRTGSField;
    
    private HoldIndicator4 hldIndField;
    
    private MatchingDenied1Choice mtchgDnlField;
    
    private UnilateralSplit1Choice unltrlSpltField;
    
    private Linkages27[] lnkgsField;
    
    /// <remarks/>
    public References16 Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    public AutomaticBorrowing2Choice AutomtcBrrwg {
        get {
            return this.automtcBrrwgField;
        }
        set {
            this.automtcBrrwgField = value;
        }
    }
    
    /// <remarks/>
    public bool RtnInd {
        get {
            return this.rtnIndField;
        }
        set {
            this.rtnIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RtnIndSpecified {
        get {
            return this.rtnIndFieldSpecified;
        }
        set {
            this.rtnIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public LinkageType1Choice Lkg {
        get {
            return this.lkgField;
        }
        set {
            this.lkgField = value;
        }
    }
    
    /// <remarks/>
    public PriorityNumeric1Choice Prty {
        get {
            return this.prtyField;
        }
        set {
            this.prtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OthrPrcg")]
    public GenericIdentification20[] OthrPrcg {
        get {
            return this.othrPrcgField;
        }
        set {
            this.othrPrcgField = value;
        }
    }
    
    /// <remarks/>
    public SettlementTransactionCondition5Code PrtlSttlmInd {
        get {
            return this.prtlSttlmIndField;
        }
        set {
            this.prtlSttlmIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrtlSttlmIndSpecified {
        get {
            return this.prtlSttlmIndFieldSpecified;
        }
        set {
            this.prtlSttlmIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public SecuritiesRTGS1Choice SctiesRTGS {
        get {
            return this.sctiesRTGSField;
        }
        set {
            this.sctiesRTGSField = value;
        }
    }
    
    /// <remarks/>
    public HoldIndicator4 HldInd {
        get {
            return this.hldIndField;
        }
        set {
            this.hldIndField = value;
        }
    }
    
    /// <remarks/>
    public MatchingDenied1Choice MtchgDnl {
        get {
            return this.mtchgDnlField;
        }
        set {
            this.mtchgDnlField = value;
        }
    }
    
    /// <remarks/>
    public UnilateralSplit1Choice UnltrlSplt {
        get {
            return this.unltrlSpltField;
        }
        set {
            this.unltrlSpltField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Lnkgs")]
    public Linkages27[] Lnkgs {
        get {
            return this.lnkgsField;
        }
        set {
            this.lnkgsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public enum SettlementTransactionCondition5Code {
    
    /// <remarks/>
    PART,
    
    /// <remarks/>
    NPAR,
    
    /// <remarks/>
    PARC,
    
    /// <remarks/>
    PARQ,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.031.001.06")]
public partial class SecuritiesAccount13 {
    
    private string idField;
    
    private GenericIdentification20 tpField;
    
    private string nmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification20 Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
}
