//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IsNullable=false)]
public partial class Document {
    
    private IntraBalanceMovementQueryResponseV01 intraBalMvmntQryRspnField;
    
    /// <remarks/>
    public IntraBalanceMovementQueryResponseV01 IntraBalMvmntQryRspn {
        get {
            return this.intraBalMvmntQryRspnField;
        }
        set {
            this.intraBalMvmntQryRspnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class IntraBalanceMovementQueryResponseV01 {
    
    private DocumentIdentification51 idField;
    
    private Pagination1 pgntnField;
    
    private MovementReport1 rptGnlDtlsField;
    
    private IntraBalanceOrOperationalError7Choice rptOrErrField;
    
    /// <remarks/>
    public DocumentIdentification51 Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public Pagination1 Pgntn {
        get {
            return this.pgntnField;
        }
        set {
            this.pgntnField = value;
        }
    }
    
    /// <remarks/>
    public MovementReport1 RptGnlDtls {
        get {
            return this.rptGnlDtlsField;
        }
        set {
            this.rptGnlDtlsField = value;
        }
    }
    
    /// <remarks/>
    public IntraBalanceOrOperationalError7Choice RptOrErr {
        get {
            return this.rptOrErrField;
        }
        set {
            this.rptOrErrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class DocumentIdentification51 {
    
    private string idField;
    
    private DateAndDateTime2Choice creDtTmField;
    
    private CopyDuplicate1Code cpyDplctField;
    
    private bool cpyDplctFieldSpecified;
    
    private PartyIdentification136 msgOrgtrField;
    
    private PartyIdentification136 msgRcptField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public DateAndDateTime2Choice CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
    
    /// <remarks/>
    public CopyDuplicate1Code CpyDplct {
        get {
            return this.cpyDplctField;
        }
        set {
            this.cpyDplctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CpyDplctSpecified {
        get {
            return this.cpyDplctFieldSpecified;
        }
        set {
            this.cpyDplctFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification136 MsgOrgtr {
        get {
            return this.msgOrgtrField;
        }
        set {
            this.msgOrgtrField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification136 MsgRcpt {
        get {
            return this.msgRcptField;
        }
        set {
            this.msgRcptField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class DateAndDateTime2Choice {
    
    private System.DateTime itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("DtTm", typeof(System.DateTime))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public System.DateTime Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    Dt,
    
    /// <remarks/>
    DtTm,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ErrorHandling3Choice {
    
    private string itemField;
    
    private ItemChoiceType10 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType10 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType10 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ErrorHandling5 {
    
    private ErrorHandling3Choice errField;
    
    private string descField;
    
    /// <remarks/>
    public ErrorHandling3Choice Err {
        get {
            return this.errField;
        }
        set {
            this.errField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class SupplementaryData1 {
    
    private string plcAndNmField;
    
    private System.Xml.XmlElement envlpField;
    
    /// <remarks/>
    public string PlcAndNm {
        get {
            return this.plcAndNmField;
        }
        set {
            this.plcAndNmField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Envlp {
        get {
            return this.envlpField;
        }
        set {
            this.envlpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class PriorityNumeric4Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Nmrc", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class GenericIdentification30 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class PartyIdentification127Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification36))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class GenericIdentification36 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class References34Choice {
    
    private string itemField;
    
    private ItemChoiceType9 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AcctSvcrTxId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IntraBalMvmntId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IntraPosMvmntId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MktInfrstrctrTxId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("OthrTxId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PoolId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("SctiesSttlmTxId", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType9 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType9 {
    
    /// <remarks/>
    AcctSvcrTxId,
    
    /// <remarks/>
    IntraBalMvmntId,
    
    /// <remarks/>
    IntraPosMvmntId,
    
    /// <remarks/>
    MktInfrstrctrTxId,
    
    /// <remarks/>
    OthrTxId,
    
    /// <remarks/>
    PoolId,
    
    /// <remarks/>
    SctiesSttlmTxId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class DocumentNumber5Choice {
    
    private object itemField;
    
    private ItemChoiceType8 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LngNb", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PrtryNb", typeof(GenericIdentification36))]
    [System.Xml.Serialization.XmlElementAttribute("ShrtNb", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType8 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType8 {
    
    /// <remarks/>
    LngNb,
    
    /// <remarks/>
    PrtryNb,
    
    /// <remarks/>
    ShrtNb,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ProcessingPosition7Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(ProcessingPosition3Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum ProcessingPosition3Code {
    
    /// <remarks/>
    AFTE,
    
    /// <remarks/>
    WITH,
    
    /// <remarks/>
    BEFO,
    
    /// <remarks/>
    INFO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class Linkages57 {
    
    private ProcessingPosition7Choice prcgPosField;
    
    private DocumentNumber5Choice msgNbField;
    
    private References34Choice refField;
    
    private PartyIdentification127Choice refOwnrField;
    
    /// <remarks/>
    public ProcessingPosition7Choice PrcgPos {
        get {
            return this.prcgPosField;
        }
        set {
            this.prcgPosField = value;
        }
    }
    
    /// <remarks/>
    public DocumentNumber5Choice MsgNb {
        get {
            return this.msgNbField;
        }
        set {
            this.msgNbField = value;
        }
    }
    
    /// <remarks/>
    public References34Choice Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification127Choice RefOwnr {
        get {
            return this.refOwnrField;
        }
        set {
            this.refOwnrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class Amount2Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AmtWthCcy", typeof(ActiveCurrencyAndAmount))]
    [System.Xml.Serialization.XmlElementAttribute("AmtWthtCcy", typeof(decimal))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ActiveCurrencyAndAmount {
    
    private string ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class FinancialInstrumentQuantity1Choice {
    
    private decimal itemField;
    
    private ItemChoiceType7 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AmtsdVal", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("FaceAmt", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType7 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType7 {
    
    /// <remarks/>
    AmtsdVal,
    
    /// <remarks/>
    FaceAmt,
    
    /// <remarks/>
    Unit,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class AmountAndDirection5 {
    
    private ActiveCurrencyAndAmount amtField;
    
    private CreditDebitCode cdtDbtField;
    
    private bool cdtDbtFieldSpecified;
    
    /// <remarks/>
    public ActiveCurrencyAndAmount Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <remarks/>
    public CreditDebitCode CdtDbt {
        get {
            return this.cdtDbtField;
        }
        set {
            this.cdtDbtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CdtDbtSpecified {
        get {
            return this.cdtDbtFieldSpecified;
        }
        set {
            this.cdtDbtFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum CreditDebitCode {
    
    /// <remarks/>
    CRDT,
    
    /// <remarks/>
    DBIT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class GenericIdentification37 {
    
    private string idField;
    
    private string issrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class AmountAndQuantityBreakdown1 {
    
    private GenericIdentification37 lotNbField;
    
    private AmountAndDirection5 lotAmtField;
    
    private FinancialInstrumentQuantity1Choice lotQtyField;
    
    private GenericIdentification30 cshSubBalTpField;
    
    /// <remarks/>
    public GenericIdentification37 LotNb {
        get {
            return this.lotNbField;
        }
        set {
            this.lotNbField = value;
        }
    }
    
    /// <remarks/>
    public AmountAndDirection5 LotAmt {
        get {
            return this.lotAmtField;
        }
        set {
            this.lotAmtField = value;
        }
    }
    
    /// <remarks/>
    public FinancialInstrumentQuantity1Choice LotQty {
        get {
            return this.lotQtyField;
        }
        set {
            this.lotQtyField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification30 CshSubBalTp {
        get {
            return this.cshSubBalTpField;
        }
        set {
            this.cshSubBalTpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class CashBalanceType3Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class CashSubBalanceTypeAndQuantityBreakdown3 {
    
    private CashBalanceType3Choice tpField;
    
    private AmountAndQuantityBreakdown1[] qtyBrkdwnField;
    
    /// <remarks/>
    public CashBalanceType3Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("QtyBrkdwn")]
    public AmountAndQuantityBreakdown1[] QtyBrkdwn {
        get {
            return this.qtyBrkdwnField;
        }
        set {
            this.qtyBrkdwnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class IntraBalanceMovement6 {
    
    private CashSubBalanceTypeAndQuantityBreakdown3 balFrField;
    
    private CashSubBalanceTypeAndQuantityBreakdown3 balToField;
    
    private Amount2Choice sttlmAmtField;
    
    private Amount2Choice sttldAmtField;
    
    private Amount2Choice prevslySttldAmtField;
    
    private Amount2Choice rmngSttlmAmtField;
    
    private DateAndDateTime2Choice intnddSttlmDtField;
    
    private DateAndDateTime2Choice fctvSttlmDtField;
    
    private System.DateTime stsDtField;
    
    private bool stsDtFieldSpecified;
    
    private GenericIdentification37 cshSubBalIdField;
    
    private Linkages57[] lnkgsField;
    
    private PriorityNumeric4Choice prtyField;
    
    private SystemPartyIdentification8 msgOrgtrField;
    
    private System.DateTime creDtTmField;
    
    private string instrPrcgAddtlDtlsField;
    
    private SupplementaryData1[] splmtryDataField;
    
    /// <remarks/>
    public CashSubBalanceTypeAndQuantityBreakdown3 BalFr {
        get {
            return this.balFrField;
        }
        set {
            this.balFrField = value;
        }
    }
    
    /// <remarks/>
    public CashSubBalanceTypeAndQuantityBreakdown3 BalTo {
        get {
            return this.balToField;
        }
        set {
            this.balToField = value;
        }
    }
    
    /// <remarks/>
    public Amount2Choice SttlmAmt {
        get {
            return this.sttlmAmtField;
        }
        set {
            this.sttlmAmtField = value;
        }
    }
    
    /// <remarks/>
    public Amount2Choice SttldAmt {
        get {
            return this.sttldAmtField;
        }
        set {
            this.sttldAmtField = value;
        }
    }
    
    /// <remarks/>
    public Amount2Choice PrevslySttldAmt {
        get {
            return this.prevslySttldAmtField;
        }
        set {
            this.prevslySttldAmtField = value;
        }
    }
    
    /// <remarks/>
    public Amount2Choice RmngSttlmAmt {
        get {
            return this.rmngSttlmAmtField;
        }
        set {
            this.rmngSttlmAmtField = value;
        }
    }
    
    /// <remarks/>
    public DateAndDateTime2Choice IntnddSttlmDt {
        get {
            return this.intnddSttlmDtField;
        }
        set {
            this.intnddSttlmDtField = value;
        }
    }
    
    /// <remarks/>
    public DateAndDateTime2Choice FctvSttlmDt {
        get {
            return this.fctvSttlmDtField;
        }
        set {
            this.fctvSttlmDtField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime StsDt {
        get {
            return this.stsDtField;
        }
        set {
            this.stsDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StsDtSpecified {
        get {
            return this.stsDtFieldSpecified;
        }
        set {
            this.stsDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification37 CshSubBalId {
        get {
            return this.cshSubBalIdField;
        }
        set {
            this.cshSubBalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Lnkgs")]
    public Linkages57[] Lnkgs {
        get {
            return this.lnkgsField;
        }
        set {
            this.lnkgsField = value;
        }
    }
    
    /// <remarks/>
    public PriorityNumeric4Choice Prty {
        get {
            return this.prtyField;
        }
        set {
            this.prtyField = value;
        }
    }
    
    /// <remarks/>
    public SystemPartyIdentification8 MsgOrgtr {
        get {
            return this.msgOrgtrField;
        }
        set {
            this.msgOrgtrField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
    
    /// <remarks/>
    public string InstrPrcgAddtlDtls {
        get {
            return this.instrPrcgAddtlDtlsField;
        }
        set {
            this.instrPrcgAddtlDtlsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
    public SupplementaryData1[] SplmtryData {
        get {
            return this.splmtryDataField;
        }
        set {
            this.splmtryDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class SystemPartyIdentification8 {
    
    private PartyIdentification136 idField;
    
    private PartyIdentification136 rspnsblPtyIdField;
    
    /// <remarks/>
    public PartyIdentification136 Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification136 RspnsblPtyId {
        get {
            return this.rspnsblPtyIdField;
        }
        set {
            this.rspnsblPtyIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class PartyIdentification136 {
    
    private PartyIdentification120Choice idField;
    
    private string lEIField;
    
    /// <remarks/>
    public PartyIdentification120Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string LEI {
        get {
            return this.lEIField;
        }
        set {
            this.lEIField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class PartyIdentification120Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NmAndAdr", typeof(NameAndAddress5))]
    [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification36))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class NameAndAddress5 {
    
    private string nmField;
    
    private PostalAddress1 adrField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress1 Adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class PostalAddress1 {
    
    private AddressType2Code adrTpField;
    
    private bool adrTpFieldSpecified;
    
    private string[] adrLineField;
    
    private string strtNmField;
    
    private string bldgNbField;
    
    private string pstCdField;
    
    private string twnNmField;
    
    private string ctrySubDvsnField;
    
    private string ctryField;
    
    /// <remarks/>
    public AddressType2Code AdrTp {
        get {
            return this.adrTpField;
        }
        set {
            this.adrTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AdrTpSpecified {
        get {
            return this.adrTpFieldSpecified;
        }
        set {
            this.adrTpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
    public string[] AdrLine {
        get {
            return this.adrLineField;
        }
        set {
            this.adrLineField = value;
        }
    }
    
    /// <remarks/>
    public string StrtNm {
        get {
            return this.strtNmField;
        }
        set {
            this.strtNmField = value;
        }
    }
    
    /// <remarks/>
    public string BldgNb {
        get {
            return this.bldgNbField;
        }
        set {
            this.bldgNbField = value;
        }
    }
    
    /// <remarks/>
    public string PstCd {
        get {
            return this.pstCdField;
        }
        set {
            this.pstCdField = value;
        }
    }
    
    /// <remarks/>
    public string TwnNm {
        get {
            return this.twnNmField;
        }
        set {
            this.twnNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsn {
        get {
            return this.ctrySubDvsnField;
        }
        set {
            this.ctrySubDvsnField = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum AddressType2Code {
    
    /// <remarks/>
    ADDR,
    
    /// <remarks/>
    PBOX,
    
    /// <remarks/>
    HOME,
    
    /// <remarks/>
    BIZZ,
    
    /// <remarks/>
    MLTO,
    
    /// <remarks/>
    DLVY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class IntraBalanceMovement5 {
    
    private CashAccount38 cshAcctField;
    
    private SystemPartyIdentification8 cshAcctOwnrField;
    
    private BranchAndFinancialInstitutionIdentification6 cshAcctSvcrField;
    
    private IntraBalanceStatusAndReason2 stsAndRsnField;
    
    private string acctOwnrTxIdField;
    
    private string acctSvcrTxIdField;
    
    private string mktInfrstrctrTxIdField;
    
    private string prcrTxIdField;
    
    private string poolIdField;
    
    private string corpActnEvtIdField;
    
    private IntraBalanceMovement6 mvmntDtlsField;
    
    /// <remarks/>
    public CashAccount38 CshAcct {
        get {
            return this.cshAcctField;
        }
        set {
            this.cshAcctField = value;
        }
    }
    
    /// <remarks/>
    public SystemPartyIdentification8 CshAcctOwnr {
        get {
            return this.cshAcctOwnrField;
        }
        set {
            this.cshAcctOwnrField = value;
        }
    }
    
    /// <remarks/>
    public BranchAndFinancialInstitutionIdentification6 CshAcctSvcr {
        get {
            return this.cshAcctSvcrField;
        }
        set {
            this.cshAcctSvcrField = value;
        }
    }
    
    /// <remarks/>
    public IntraBalanceStatusAndReason2 StsAndRsn {
        get {
            return this.stsAndRsnField;
        }
        set {
            this.stsAndRsnField = value;
        }
    }
    
    /// <remarks/>
    public string AcctOwnrTxId {
        get {
            return this.acctOwnrTxIdField;
        }
        set {
            this.acctOwnrTxIdField = value;
        }
    }
    
    /// <remarks/>
    public string AcctSvcrTxId {
        get {
            return this.acctSvcrTxIdField;
        }
        set {
            this.acctSvcrTxIdField = value;
        }
    }
    
    /// <remarks/>
    public string MktInfrstrctrTxId {
        get {
            return this.mktInfrstrctrTxIdField;
        }
        set {
            this.mktInfrstrctrTxIdField = value;
        }
    }
    
    /// <remarks/>
    public string PrcrTxId {
        get {
            return this.prcrTxIdField;
        }
        set {
            this.prcrTxIdField = value;
        }
    }
    
    /// <remarks/>
    public string PoolId {
        get {
            return this.poolIdField;
        }
        set {
            this.poolIdField = value;
        }
    }
    
    /// <remarks/>
    public string CorpActnEvtId {
        get {
            return this.corpActnEvtIdField;
        }
        set {
            this.corpActnEvtIdField = value;
        }
    }
    
    /// <remarks/>
    public IntraBalanceMovement6 MvmntDtls {
        get {
            return this.mvmntDtlsField;
        }
        set {
            this.mvmntDtlsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class CashAccount38 {
    
    private AccountIdentification4Choice idField;
    
    private CashAccountType2Choice tpField;
    
    private string ccyField;
    
    private string nmField;
    
    private ProxyAccountIdentification1 prxyField;
    
    /// <remarks/>
    public AccountIdentification4Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public CashAccountType2Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public ProxyAccountIdentification1 Prxy {
        get {
            return this.prxyField;
        }
        set {
            this.prxyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class AccountIdentification4Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAN", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericAccountIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class GenericAccountIdentification1 {
    
    private string idField;
    
    private AccountSchemeName1Choice schmeNmField;
    
    private string issrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public AccountSchemeName1Choice SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class AccountSchemeName1Choice {
    
    private string itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class CashAccountType2Choice {
    
    private string itemField;
    
    private ItemChoiceType2 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType2 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType2 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ProxyAccountIdentification1 {
    
    private ProxyAccountType1Choice tpField;
    
    private string idField;
    
    /// <remarks/>
    public ProxyAccountType1Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ProxyAccountType1Choice {
    
    private string itemField;
    
    private ItemChoiceType3 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType3 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType3 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class BranchAndFinancialInstitutionIdentification6 {
    
    private FinancialInstitutionIdentification18 finInstnIdField;
    
    private BranchData3 brnchIdField;
    
    /// <remarks/>
    public FinancialInstitutionIdentification18 FinInstnId {
        get {
            return this.finInstnIdField;
        }
        set {
            this.finInstnIdField = value;
        }
    }
    
    /// <remarks/>
    public BranchData3 BrnchId {
        get {
            return this.brnchIdField;
        }
        set {
            this.brnchIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class FinancialInstitutionIdentification18 {
    
    private string bICFIField;
    
    private ClearingSystemMemberIdentification2 clrSysMmbIdField;
    
    private string lEIField;
    
    private string nmField;
    
    private PostalAddress24 pstlAdrField;
    
    private GenericFinancialIdentification1 othrField;
    
    /// <remarks/>
    public string BICFI {
        get {
            return this.bICFIField;
        }
        set {
            this.bICFIField = value;
        }
    }
    
    /// <remarks/>
    public ClearingSystemMemberIdentification2 ClrSysMmbId {
        get {
            return this.clrSysMmbIdField;
        }
        set {
            this.clrSysMmbIdField = value;
        }
    }
    
    /// <remarks/>
    public string LEI {
        get {
            return this.lEIField;
        }
        set {
            this.lEIField = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress24 PstlAdr {
        get {
            return this.pstlAdrField;
        }
        set {
            this.pstlAdrField = value;
        }
    }
    
    /// <remarks/>
    public GenericFinancialIdentification1 Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ClearingSystemMemberIdentification2 {
    
    private ClearingSystemIdentification2Choice clrSysIdField;
    
    private string mmbIdField;
    
    /// <remarks/>
    public ClearingSystemIdentification2Choice ClrSysId {
        get {
            return this.clrSysIdField;
        }
        set {
            this.clrSysIdField = value;
        }
    }
    
    /// <remarks/>
    public string MmbId {
        get {
            return this.mmbIdField;
        }
        set {
            this.mmbIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ClearingSystemIdentification2Choice {
    
    private string itemField;
    
    private ItemChoiceType4 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType4 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType4 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class PostalAddress24 {
    
    private AddressType3Choice adrTpField;
    
    private string deptField;
    
    private string subDeptField;
    
    private string strtNmField;
    
    private string bldgNbField;
    
    private string bldgNmField;
    
    private string flrField;
    
    private string pstBxField;
    
    private string roomField;
    
    private string pstCdField;
    
    private string twnNmField;
    
    private string twnLctnNmField;
    
    private string dstrctNmField;
    
    private string ctrySubDvsnField;
    
    private string ctryField;
    
    private string[] adrLineField;
    
    /// <remarks/>
    public AddressType3Choice AdrTp {
        get {
            return this.adrTpField;
        }
        set {
            this.adrTpField = value;
        }
    }
    
    /// <remarks/>
    public string Dept {
        get {
            return this.deptField;
        }
        set {
            this.deptField = value;
        }
    }
    
    /// <remarks/>
    public string SubDept {
        get {
            return this.subDeptField;
        }
        set {
            this.subDeptField = value;
        }
    }
    
    /// <remarks/>
    public string StrtNm {
        get {
            return this.strtNmField;
        }
        set {
            this.strtNmField = value;
        }
    }
    
    /// <remarks/>
    public string BldgNb {
        get {
            return this.bldgNbField;
        }
        set {
            this.bldgNbField = value;
        }
    }
    
    /// <remarks/>
    public string BldgNm {
        get {
            return this.bldgNmField;
        }
        set {
            this.bldgNmField = value;
        }
    }
    
    /// <remarks/>
    public string Flr {
        get {
            return this.flrField;
        }
        set {
            this.flrField = value;
        }
    }
    
    /// <remarks/>
    public string PstBx {
        get {
            return this.pstBxField;
        }
        set {
            this.pstBxField = value;
        }
    }
    
    /// <remarks/>
    public string Room {
        get {
            return this.roomField;
        }
        set {
            this.roomField = value;
        }
    }
    
    /// <remarks/>
    public string PstCd {
        get {
            return this.pstCdField;
        }
        set {
            this.pstCdField = value;
        }
    }
    
    /// <remarks/>
    public string TwnNm {
        get {
            return this.twnNmField;
        }
        set {
            this.twnNmField = value;
        }
    }
    
    /// <remarks/>
    public string TwnLctnNm {
        get {
            return this.twnLctnNmField;
        }
        set {
            this.twnLctnNmField = value;
        }
    }
    
    /// <remarks/>
    public string DstrctNm {
        get {
            return this.dstrctNmField;
        }
        set {
            this.dstrctNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsn {
        get {
            return this.ctrySubDvsnField;
        }
        set {
            this.ctrySubDvsnField = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
    public string[] AdrLine {
        get {
            return this.adrLineField;
        }
        set {
            this.adrLineField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class AddressType3Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(AddressType2Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class GenericFinancialIdentification1 {
    
    private string idField;
    
    private FinancialIdentificationSchemeName1Choice schmeNmField;
    
    private string issrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public FinancialIdentificationSchemeName1Choice SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class FinancialIdentificationSchemeName1Choice {
    
    private string itemField;
    
    private ItemChoiceType5 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType5 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType5 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class BranchData3 {
    
    private string idField;
    
    private string lEIField;
    
    private string nmField;
    
    private PostalAddress24 pstlAdrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string LEI {
        get {
            return this.lEIField;
        }
        set {
            this.lEIField = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress24 PstlAdr {
        get {
            return this.pstlAdrField;
        }
        set {
            this.pstlAdrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class IntraBalanceStatusAndReason2 {
    
    private ProcessingStatus67Choice[] prcgStsField;
    
    private SettlementStatus16Choice[] sttlmStsField;
    
    private ProprietaryReason4 sttldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PrcgSts")]
    public ProcessingStatus67Choice[] PrcgSts {
        get {
            return this.prcgStsField;
        }
        set {
            this.prcgStsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SttlmSts")]
    public SettlementStatus16Choice[] SttlmSts {
        get {
            return this.sttlmStsField;
        }
        set {
            this.sttlmStsField = value;
        }
    }
    
    /// <remarks/>
    public ProprietaryReason4 Sttld {
        get {
            return this.sttldField;
        }
        set {
            this.sttldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ProcessingStatus67Choice {
    
    private object itemField;
    
    private ItemChoiceType6 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AckdAccptd", typeof(AcknowledgedAcceptedStatus21Choice))]
    [System.Xml.Serialization.XmlElementAttribute("Canc", typeof(CancellationStatus14Choice))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(ProprietaryStatusAndReason6))]
    [System.Xml.Serialization.XmlElementAttribute("Rjctd", typeof(RejectionOrRepairStatus38Choice))]
    [System.Xml.Serialization.XmlElementAttribute("Rpr", typeof(RejectionOrRepairStatus38Choice))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType6 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class AcknowledgedAcceptedStatus21Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(AcknowledgementReason9))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum NoReasonCode {
    
    /// <remarks/>
    NORE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class AcknowledgementReason9 {
    
    private AcknowledgementReason12Choice cdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public AcknowledgementReason12Choice Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class AcknowledgementReason12Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(AcknowledgementReason5Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum AcknowledgementReason5Code {
    
    /// <remarks/>
    ADEA,
    
    /// <remarks/>
    SMPG,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    CDCY,
    
    /// <remarks/>
    CDRG,
    
    /// <remarks/>
    CDRE,
    
    /// <remarks/>
    NSTP,
    
    /// <remarks/>
    RQWV,
    
    /// <remarks/>
    LATE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class CancellationStatus14Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(CancellationReason9))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class CancellationReason9 {
    
    private CancellationReason19Choice cdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public CancellationReason19Choice Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class CancellationReason19Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(CancelledStatusReason13Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum CancelledStatusReason13Code {
    
    /// <remarks/>
    CANI,
    
    /// <remarks/>
    CANS,
    
    /// <remarks/>
    CSUB,
    
    /// <remarks/>
    CXLR,
    
    /// <remarks/>
    CANT,
    
    /// <remarks/>
    CANZ,
    
    /// <remarks/>
    CORP,
    
    /// <remarks/>
    SCEX,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    CTHP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ProprietaryStatusAndReason6 {
    
    private GenericIdentification30 prtryStsField;
    
    private ProprietaryReason4[] prtryRsnField;
    
    /// <remarks/>
    public GenericIdentification30 PrtrySts {
        get {
            return this.prtryStsField;
        }
        set {
            this.prtryStsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PrtryRsn")]
    public ProprietaryReason4[] PrtryRsn {
        get {
            return this.prtryRsnField;
        }
        set {
            this.prtryRsnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class ProprietaryReason4 {
    
    private GenericIdentification30 rsnField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public GenericIdentification30 Rsn {
        get {
            return this.rsnField;
        }
        set {
            this.rsnField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class RejectionOrRepairStatus38Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(RejectionOrRepairReason32))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class RejectionOrRepairReason32 {
    
    private RejectionAndRepairReason32Choice[] cdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd")]
    public RejectionAndRepairReason32Choice[] Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class RejectionAndRepairReason32Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(RejectionReason33Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum RejectionReason33Code {
    
    /// <remarks/>
    CASH,
    
    /// <remarks/>
    ADEA,
    
    /// <remarks/>
    DMON,
    
    /// <remarks/>
    NCRR,
    
    /// <remarks/>
    LATE,
    
    /// <remarks/>
    INVL,
    
    /// <remarks/>
    INVB,
    
    /// <remarks/>
    INVN,
    
    /// <remarks/>
    VALR,
    
    /// <remarks/>
    MONY,
    
    /// <remarks/>
    CAEV,
    
    /// <remarks/>
    DDAT,
    
    /// <remarks/>
    REFE,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    DQUA,
    
    /// <remarks/>
    DSEC,
    
    /// <remarks/>
    MINO,
    
    /// <remarks/>
    MUNO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01", IncludeInSchema=false)]
public enum ItemChoiceType6 {
    
    /// <remarks/>
    AckdAccptd,
    
    /// <remarks/>
    Canc,
    
    /// <remarks/>
    Prtry,
    
    /// <remarks/>
    Rjctd,
    
    /// <remarks/>
    Rpr,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class SettlementStatus16Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Flng", typeof(FailingStatus9Choice))]
    [System.Xml.Serialization.XmlElementAttribute("Pdg", typeof(PendingStatus36Choice))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(ProprietaryStatusAndReason6))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class FailingStatus9Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(FailingReason7))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class FailingReason7 {
    
    private FailingReason7Choice cdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public FailingReason7Choice Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class FailingReason7Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(FailingReason3Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum FailingReason3Code {
    
    /// <remarks/>
    AWMO,
    
    /// <remarks/>
    BYIY,
    
    /// <remarks/>
    CLAT,
    
    /// <remarks/>
    ADEA,
    
    /// <remarks/>
    CANR,
    
    /// <remarks/>
    CAIS,
    
    /// <remarks/>
    OBJT,
    
    /// <remarks/>
    AWSH,
    
    /// <remarks/>
    PHSE,
    
    /// <remarks/>
    STCD,
    
    /// <remarks/>
    DOCY,
    
    /// <remarks/>
    MLAT,
    
    /// <remarks/>
    DOCC,
    
    /// <remarks/>
    BLOC,
    
    /// <remarks/>
    CHAS,
    
    /// <remarks/>
    NEWI,
    
    /// <remarks/>
    CLAC,
    
    /// <remarks/>
    MUNO,
    
    /// <remarks/>
    GLOB,
    
    /// <remarks/>
    PREA,
    
    /// <remarks/>
    PART,
    
    /// <remarks/>
    NOFX,
    
    /// <remarks/>
    CMON,
    
    /// <remarks/>
    YCOL,
    
    /// <remarks/>
    COLL,
    
    /// <remarks/>
    DEPO,
    
    /// <remarks/>
    FLIM,
    
    /// <remarks/>
    INCA,
    
    /// <remarks/>
    LINK,
    
    /// <remarks/>
    LACK,
    
    /// <remarks/>
    LALO,
    
    /// <remarks/>
    MONY,
    
    /// <remarks/>
    NCON,
    
    /// <remarks/>
    REFS,
    
    /// <remarks/>
    SDUT,
    
    /// <remarks/>
    BATC,
    
    /// <remarks/>
    CYCL,
    
    /// <remarks/>
    SBLO,
    
    /// <remarks/>
    CPEC,
    
    /// <remarks/>
    MINO,
    
    /// <remarks/>
    IAAD,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    PHCK,
    
    /// <remarks/>
    BENO,
    
    /// <remarks/>
    BOTH,
    
    /// <remarks/>
    CLHT,
    
    /// <remarks/>
    DENO,
    
    /// <remarks/>
    DISA,
    
    /// <remarks/>
    DKNY,
    
    /// <remarks/>
    FROZ,
    
    /// <remarks/>
    LAAW,
    
    /// <remarks/>
    LATE,
    
    /// <remarks/>
    LIQU,
    
    /// <remarks/>
    PRCY,
    
    /// <remarks/>
    REGT,
    
    /// <remarks/>
    SETS,
    
    /// <remarks/>
    CERT,
    
    /// <remarks/>
    PRSY,
    
    /// <remarks/>
    INBC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class PendingStatus36Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
    [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(PendingReason14))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class PendingReason14 {
    
    private PendingReason26Choice cdField;
    
    private string addtlRsnInfField;
    
    /// <remarks/>
    public PendingReason26Choice Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlRsnInf {
        get {
            return this.addtlRsnInfField;
        }
        set {
            this.addtlRsnInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class PendingReason26Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(PendingReason10Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum PendingReason10Code {
    
    /// <remarks/>
    AWMO,
    
    /// <remarks/>
    ADEA,
    
    /// <remarks/>
    CAIS,
    
    /// <remarks/>
    REFU,
    
    /// <remarks/>
    AWSH,
    
    /// <remarks/>
    PHSE,
    
    /// <remarks/>
    TAMM,
    
    /// <remarks/>
    DOCY,
    
    /// <remarks/>
    DOCC,
    
    /// <remarks/>
    BLOC,
    
    /// <remarks/>
    CHAS,
    
    /// <remarks/>
    NEWI,
    
    /// <remarks/>
    CLAC,
    
    /// <remarks/>
    MUNO,
    
    /// <remarks/>
    GLOB,
    
    /// <remarks/>
    PREA,
    
    /// <remarks/>
    PART,
    
    /// <remarks/>
    NMAS,
    
    /// <remarks/>
    NOFX,
    
    /// <remarks/>
    CMON,
    
    /// <remarks/>
    YCOL,
    
    /// <remarks/>
    COLL,
    
    /// <remarks/>
    DEPO,
    
    /// <remarks/>
    FLIM,
    
    /// <remarks/>
    INCA,
    
    /// <remarks/>
    LINK,
    
    /// <remarks/>
    FUTU,
    
    /// <remarks/>
    LACK,
    
    /// <remarks/>
    LALO,
    
    /// <remarks/>
    MONY,
    
    /// <remarks/>
    NCON,
    
    /// <remarks/>
    REFS,
    
    /// <remarks/>
    SDUT,
    
    /// <remarks/>
    BATC,
    
    /// <remarks/>
    CYCL,
    
    /// <remarks/>
    SBLO,
    
    /// <remarks/>
    CPEC,
    
    /// <remarks/>
    MINO,
    
    /// <remarks/>
    IAAD,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    PHCK,
    
    /// <remarks/>
    BENO,
    
    /// <remarks/>
    BOTH,
    
    /// <remarks/>
    CLHT,
    
    /// <remarks/>
    DENO,
    
    /// <remarks/>
    DISA,
    
    /// <remarks/>
    DKNY,
    
    /// <remarks/>
    FROZ,
    
    /// <remarks/>
    LAAW,
    
    /// <remarks/>
    LATE,
    
    /// <remarks/>
    LIQU,
    
    /// <remarks/>
    PRCY,
    
    /// <remarks/>
    REGT,
    
    /// <remarks/>
    SETS,
    
    /// <remarks/>
    CERT,
    
    /// <remarks/>
    PRSY,
    
    /// <remarks/>
    INBC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class IntraBalanceMovements3 {
    
    private CashAccount38 cshAcctField;
    
    private SystemPartyIdentification8 cshAcctOwnrField;
    
    private BranchAndFinancialInstitutionIdentification6 cshAcctSvcrField;
    
    private IntraBalanceStatusAndReason2 stsAndRsnField;
    
    private IntraBalanceMovement5[] mvmntField;
    
    /// <remarks/>
    public CashAccount38 CshAcct {
        get {
            return this.cshAcctField;
        }
        set {
            this.cshAcctField = value;
        }
    }
    
    /// <remarks/>
    public SystemPartyIdentification8 CshAcctOwnr {
        get {
            return this.cshAcctOwnrField;
        }
        set {
            this.cshAcctOwnrField = value;
        }
    }
    
    /// <remarks/>
    public BranchAndFinancialInstitutionIdentification6 CshAcctSvcr {
        get {
            return this.cshAcctSvcrField;
        }
        set {
            this.cshAcctSvcrField = value;
        }
    }
    
    /// <remarks/>
    public IntraBalanceStatusAndReason2 StsAndRsn {
        get {
            return this.stsAndRsnField;
        }
        set {
            this.stsAndRsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mvmnt")]
    public IntraBalanceMovement5[] Mvmnt {
        get {
            return this.mvmntField;
        }
        set {
            this.mvmntField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class IntraBalanceOrOperationalError7Choice {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mvmnts", typeof(IntraBalanceMovements3))]
    [System.Xml.Serialization.XmlElementAttribute("OprlErr", typeof(ErrorHandling5))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class MovementReport1 {
    
    private string qryRefField;
    
    private string rptIdField;
    
    private MovementResponseType1Code qryTpField;
    
    private bool actvtyIndField;
    
    /// <remarks/>
    public string QryRef {
        get {
            return this.qryRefField;
        }
        set {
            this.qryRefField = value;
        }
    }
    
    /// <remarks/>
    public string RptId {
        get {
            return this.rptIdField;
        }
        set {
            this.rptIdField = value;
        }
    }
    
    /// <remarks/>
    public MovementResponseType1Code QryTp {
        get {
            return this.qryTpField;
        }
        set {
            this.qryTpField = value;
        }
    }
    
    /// <remarks/>
    public bool ActvtyInd {
        get {
            return this.actvtyIndField;
        }
        set {
            this.actvtyIndField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum MovementResponseType1Code {
    
    /// <remarks/>
    FULL,
    
    /// <remarks/>
    STTS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public partial class Pagination1 {
    
    private string pgNbField;
    
    private bool lastPgIndField;
    
    /// <remarks/>
    public string PgNb {
        get {
            return this.pgNbField;
        }
        set {
            this.pgNbField = value;
        }
    }
    
    /// <remarks/>
    public bool LastPgInd {
        get {
            return this.lastPgIndField;
        }
        set {
            this.lastPgIndField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.079.001.01")]
public enum CopyDuplicate1Code {
    
    /// <remarks/>
    CODU,
    
    /// <remarks/>
    COPY,
    
    /// <remarks/>
    DUPL,
}
