//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.008.002.01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.008.002.01", IsNullable=false)]
public partial class Document {
    
    private camt00800201 camt00800201Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("camt.008.002.01")]
    public camt00800201 camt00800201 {
        get {
            return this.camt00800201Field;
        }
        set {
            this.camt00800201Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="camt.008.002.01", Namespace="urn:iso:std:iso:20022:tech:xsd:camt.008.002.01")]
public partial class camt00800201 {
    
    private CaseAssignment assgnmtField;
    
    private Case caseField;
    
    private PaymentInstructionExtract undrlygField;
    
    private DebitAuthorisationDetails justfnField;
    
    /// <remarks/>
    public CaseAssignment Assgnmt {
        get {
            return this.assgnmtField;
        }
        set {
            this.assgnmtField = value;
        }
    }
    
    /// <remarks/>
    public Case Case {
        get {
            return this.caseField;
        }
        set {
            this.caseField = value;
        }
    }
    
    /// <remarks/>
    public PaymentInstructionExtract Undrlyg {
        get {
            return this.undrlygField;
        }
        set {
            this.undrlygField = value;
        }
    }
    
    /// <remarks/>
    public DebitAuthorisationDetails Justfn {
        get {
            return this.justfnField;
        }
        set {
            this.justfnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.008.002.01")]
public partial class CaseAssignment {
    
    private string idField;
    
    private string assgnrField;
    
    private string assgneField;
    
    private System.DateTime creDtTmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Assgnr {
        get {
            return this.assgnrField;
        }
        set {
            this.assgnrField = value;
        }
    }
    
    /// <remarks/>
    public string Assgne {
        get {
            return this.assgneField;
        }
        set {
            this.assgneField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.008.002.01")]
public partial class DebitAuthorisationDetails {
    
    private CancellationReason1Code cxlRsnField;
    
    private CurrencyAndAmount amtToDbtField;
    
    private System.DateTime valDtToDbtField;
    
    private bool valDtToDbtFieldSpecified;
    
    /// <remarks/>
    public CancellationReason1Code CxlRsn {
        get {
            return this.cxlRsnField;
        }
        set {
            this.cxlRsnField = value;
        }
    }
    
    /// <remarks/>
    public CurrencyAndAmount AmtToDbt {
        get {
            return this.amtToDbtField;
        }
        set {
            this.amtToDbtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ValDtToDbt {
        get {
            return this.valDtToDbtField;
        }
        set {
            this.valDtToDbtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValDtToDbtSpecified {
        get {
            return this.valDtToDbtFieldSpecified;
        }
        set {
            this.valDtToDbtFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.008.002.01")]
public enum CancellationReason1Code {
    
    /// <remarks/>
    CUST,
    
    /// <remarks/>
    DUPL,
    
    /// <remarks/>
    AGNT,
    
    /// <remarks/>
    CURR,
    
    /// <remarks/>
    UPAY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.008.002.01")]
public partial class CurrencyAndAmount {
    
    private string ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.008.002.01")]
public partial class PaymentInstructionExtract {
    
    private string assgnrInstrIdField;
    
    private string assgneInstrIdField;
    
    private CurrencyAndAmount ccyAmtField;
    
    private System.DateTime valDtField;
    
    private bool valDtFieldSpecified;
    
    /// <remarks/>
    public string AssgnrInstrId {
        get {
            return this.assgnrInstrIdField;
        }
        set {
            this.assgnrInstrIdField = value;
        }
    }
    
    /// <remarks/>
    public string AssgneInstrId {
        get {
            return this.assgneInstrIdField;
        }
        set {
            this.assgneInstrIdField = value;
        }
    }
    
    /// <remarks/>
    public CurrencyAndAmount CcyAmt {
        get {
            return this.ccyAmtField;
        }
        set {
            this.ccyAmtField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ValDt {
        get {
            return this.valDtField;
        }
        set {
            this.valDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValDtSpecified {
        get {
            return this.valDtFieldSpecified;
        }
        set {
            this.valDtFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:camt.008.002.01")]
public partial class Case {
    
    private string idField;
    
    private string cretrField;
    
    private bool reopCaseIndctnField;
    
    private bool reopCaseIndctnFieldSpecified;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Cretr {
        get {
            return this.cretrField;
        }
        set {
            this.cretrField = value;
        }
    }
    
    /// <remarks/>
    public bool ReopCaseIndctn {
        get {
            return this.reopCaseIndctnField;
        }
        set {
            this.reopCaseIndctnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReopCaseIndctnSpecified {
        get {
            return this.reopCaseIndctnFieldSpecified;
        }
        set {
            this.reopCaseIndctnFieldSpecified = value;
        }
    }
}
